#config_version=5
# accelerate river d (right river, bottom to top)
# When ending timer handler_x starts an keeps the mode alive for two seconds so
# the mode code has time to shut down the accelerate rules. When the magnets
# should be triggering the river mouths flash. After each should be
# trigger, the accelerate rule is turned off for 2 seconds. This prevents
# the ball from getting trapped trying to exit upslope. It also prevents
# overheating.
# Consider having show player just blink the mouth at ball exit not the whole river.
mode:
  start_events:
    - accelerate_rivers
    - mode_hades_bug_game_starting
  stop_events: timer_handler_d_complete
  code: river_d_fast.river_d_fast
  priority: 6400 #Must be above hades' show player

event_player:
  mode_river_d_fast_started: accelerate_d|1s
  left_river_top_to_bottom_hit: normalize_d
  timer_cooldown_d_complete: accelerate_d
  mode_hades_bonus_game_stopped: normalize_d
  mode_hades_bug_game_stopped: normalize_d

timers:
  handler_d:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 2s
    control_events:
      - action: restart
        event: mode_hades_bonus_game_stopped
      - action: restart
        event: mode_hades_bug_game_stopped
  cooldown_d:
    start_value: 2
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: restart
        event: right_river_bottom_to_top_hit

#show_player:
#  right_river_bottom_to_top_hit:
#    show_hades_right_mouths_red:
#      speed: 5
#      loops: 0
