#config_version=5
#There is a bug in this relating to slide positioning.  This needs to be targetes to score_lcd but doiing so does not parse properly.  work around is to not use PF lcd and adjust y position
mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true
high_score:
  _overwrite: true
  enter_initials_timeout: 60
  award_slide_display_time: 4s
  # define your high score categories and the awards
  categories: !!omap
    - score:
        - GRAND CHAMPION
        - HIGH SCORE 1
        - HIGH SCORE 2
        - HIGH SCORE 3
        - HIGH SCORE 4
        - HIGH SCORE 5
        - HIGH SCORE 6
        - HIGH SCORE 7
        - HIGH SCORE 8
        - HIGH SCORE 9
        - HIGH SCORE 10
#    - Sisyphus Completed:
#        - SISYPHUS BALL CHAMP
  # set the defaults
  defaults:
    score:
      - MPF: 100000
      - BRI: 90000
      - JAN: 80000
      - QUI: 70000
      - MAR: 60000
      - JOH: 50000
      - ELI: 40000
      - MIK: 30000
      - ANT: 20000
      - KJA: 15000
      - CAM: 10000
#    sisyphus_completions:
#      - COM: 10
# optional: change the slides (you can omit all the following)

coil_player:
  high_score_enter_initials:
    c_u_knocker:
      action: pulse
      pulse_ms: 30
  high_score_award_display:
    c_u_knocker:
      action: pulse
      pulse_ms: 30


slide_player:
  _overwrite: true
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display
slides:
  _overwrite: true
  high_score_enter_initials:
    - type: image
      image: high_score_background
      z: 0
      anchor_y: top
      y: 100%
    - type: text
      style: big
      font_size: 100
      font_name: greekgods3
      text: PLAYER (player_num)
      color: ffff00
      x: 50%
      y: 90%
      z: 1
    - type: text
      style: big
      font_size: 100
      font_name: greekgods3
      text: (award)
      color: f0f0f0
      x: 50%
      y: 85%
      z: 1
    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      style: big
      font_size: 100
      font_name: greekgods3
      max_chars: 3
      x: 50%
      y: 40%
      shift_left_event: s_left_flipper_active
      shift_right_event: s_right_flipper_active ##############Update docs with _active
      select_event: s_start_active  ####Update here too
      color: ff0000
      z: 1
    - type: text
      style: big
      text: '<       >'
      font_size: 100
      font_name: greekgods3
      x: 50%
      y: 40%
      color: ff0000
      z: 1
    - type: text
      text: ''
      key: high_score
      font_size: 200
      font_name: greekgods3
      style: big
      x: 50%
      y: 45%
      color: ff00ff
      z: 1
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.3s
            easing: in_out_quint
          - property: opacity
            value: 0
            duration: 0.3s
            repeat: true
            easing: in_out_quint
  high_score_award_display:
    - type: image
      image: high_score_background
      z: 0
      anchor_y: top
      y: 100%
    - type: text
      text: (player_name)
      font_size: 100
      font_name: greekgods3
      style: big
      anchor_y: middle
      anchor_x: middle
      x: middle
      y: middle
      color: 00ff00
      z: 1
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.05s
          - property: opacity
            value: 0
            duration: 0.05s
            repeat: true
    - type: text
      text: (award)
      font_size: 100
      font_name: greekgods3
      style: big
      x: 50%
      y: 95%
      color: 0000ff
      z: 1
    - type: text
      text: (value)
      style: big
      x: 60%
      y: 50%
      color: 4040FF
      font_size: 100
      font_name: greekgods3
      number_grouping: true
      min_digits: 2
      z: 1
