#config_version=5
# This mode starts on a double hit to the left ramp.  It shuts down if the ball save is used or a 1 min timer expires. It set up a shot for the left outlane that will disable during mb.
# It uses a multiball without a shoot again to serve the ball.
mode:
  priority: 250 # range 100-1M
  start_events:
    - double_left_ramp_hit
  stop_events:
    - ball_ended
    - multiball_left_outlane_started
    - timer_left_bs_expiration_complete

multiballs:
  left_outlane:
    source_playfield: earth_pf
    ball_count: 1
    ball_count_type: add #total # increase number of playfield balls to count
    shoot_again: 0s #ball save for MB 10 sec default
    start_events: left_outlane_banked_ballsave_hit
    debug: true

timers:
  left_bs_expiration:
    start_value: 4
    end_value: 0
    direction: down
    tick_interval: 15s
    control_events:
      - event: mode_banked_l_bs_started #ball_waiting_to_eject_from_scoop_done
        action: restart #reset to starting value and start
      - event: banked_l_ballsave_double_left_ramp_hit{device.timers.left_bs_expiration.ticks<6}
        action: add
        value: 2
shots:
  left_outlane_banked_ballsave:  #. When shot is hit it triggers a 1 ball MB effectively returning ball to play
    playfield: earth_pf
    disable_events:
      - multiball_poseidon_ramp_started
      - multiball_olympus_ramp_started  #add hidden hole mb when written
    enable_events:
      - mode_banked_l_bs_started
      - multiball_poseidon_ramp_ended #re-enable when a mb ends.  This should not start the mode if not already running.
      - multiball_olympus_ramp_ended  #add hidden hole mb when written
    switches:
      - s_left_outlane
  banked_l_ballsave_double_left_ramp: #used to add time to banked ball save mode
    playfield: earth_pf
    profile: off_on
    enable_events:
      - timer_base_left_ramp_tick{device.timers.base_left_ramp.ticks==6}
    disable_events:
      - timer_base_left_ramp_complete
    hit_events:
      - left_ramp_hit

#sequence_shots:
#  banked_l_ballsave_double_left_ramp: #used to add time to banked ball save mode
#    playfield: earth_pf
#    delay_event_list:
#      left_ramp_hit: 2s #Dont start timing the sequence until 2 sec post this event
#    event_sequence:
#      - left_ramp_hit                     #cant use same event twice
#      - s_poseidon_lock_distal_active
#    sequence_timeout: 12s

#Instead add a widget to the BB screen
#slide_player:
#  mode_banked_l_bs_started:
#    tell_player_banked_l_bs:
#      target: playfield_lcd
#      background_color: black
#      widgets:
#      - type: text
#        text: Left Outlane
#        color: FFFFFF
#        y: 60%
#        anchor_x: center
#        anchor_y: bottom
#        font_size: 60
#        z: 200
#      - type: text
#        text: Ballsave Engaged!
#        color: FFFFFF
#        y: 40%
#        anchor_x: center
#        anchor_y: bottom
#        font_size: 60
#        z: 200

show_player:
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks>5}:
    show_left_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6: #Start the beginning show
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==5}:
    show_left_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_5: #Start the beginning show
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==4}:
    show_left_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_4: #Start the beginning show
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==3}:
    show_left_shoulder_1:
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_3:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==2}:
    show_left_shoulder_1:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_2:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==1}:
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_1:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==0}:
    show_left_shoulder_1:
      action: stop

sound_player:
  mode_banked_l_bs_started: comboballsavelocked
  banked_l_ballsave_double_left_ramp_hit{device.timers.left_bs_expiration.ticks<6}: timeadded
