#config_version=5
# This mode starts on a double hit to the left ramp.  It shuts down if the ball save is used or a 1 min timer expires. It set up a shot for the left outlane that will disable during mb.
# It uses a multiball without a shoot again to serve the ball.
mode:
  priority: 250 # range 100-1M
  start_events:
    - double_left_ramp_hit
  stop_events:
    - ball_ended
    - multiball_left_outlane_started
    - timer_left_bs_expiration_complete

multiballs:
  left_outlane:
    source_playfield: earth_pf
    ball_count: 1
    ball_count_type: add #total # increase number of playfield balls to count
    shoot_again: 0s #ball save for MB 10 sec default
    start_events: left_outlane_banked_ballsave_hit
    debug: true

timers:
  left_bs_expiration:
    start_value: 4
    end_value: 0
    direction: down
    tick_interval: 15s
    control_events:
      - action: restart #reset to starting value and start
        event: mode_banked_l_bs_started #ball_waiting_to_eject_from_scoop_done
      - action: restart
        event: double_left_ramp_hit #reset the timer if hit again

shots:
  left_outlane_banked_ballsave:  #This shots with a 2x shot to the left ramp. When shot is hit it triggers a 1 ball MB effectively returning ball to play
    playfield: earth_pf
    disable_events:
      - multiball_celest_mb_started      #disable when a mb starts.
      - multiball_poseidon_ramp_started
      - multiball_olympus_ramp_started  #add hidden hole mb when written
    enable_events:
      - mode_banked_l_bs_started
      - multiball_celest_mb_ended      #re-enable when a mb ends.  This should not start the mode if not already running.
      - multiball_poseidon_ramp_ended
      - multiball_olympus_ramp_ended  #add hidden hole mb when written
    switches:
      - s_left_outlane
    # reset_events: ball_started

slide_player:
  mode_banked_l_bs_started:
    tell_player_banked_l_bs:
      target: playfield_lcd
      background_color: black
      widgets:
      - type: text
        text: Left Outlane
        color: FFFFFF
        y: 60%
        anchor_x: center
        anchor_y: bottom
        font_size: 60
        z: 200
      - type: text
        text: Ballsave Engaged!
        color: FFFFFF
        y: 40%
        anchor_x: center
        anchor_y: bottom
        font_size: 60
        z: 200

show_player:
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==4}:
    show_left_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4: #Start the beginning show
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==3}:
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_3:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==2}:
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_2:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==1}:
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_1:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==0}:
    show_left_shoulder_1:
      action: stop

sound_player:
  mode_banked_l_bs_started: comboballsavelocked
#  double_left_ramp_hit:  comboballsavelocked
