#config_version=5
# This mode starts on a double hit to the left ramp.  It shuts down if the ball save
# is used or a 1 min mode timer expires. A repeat hit to the ramp will add time to the
# mode. The mode sets up an outlane shot that in turn starts the timer of the ball save.
# Another timer in this mode then chain-activates the timer. This may be possible to skip
# the timer by instead having the ball save save the ball by monitoring for the event
# ball_save_(name)_timer_start
# Also this mode runs the show that indictes the ball save is available.
# Things to do: 1. figure out why double hits to ramp dont
# always add more time to the outlane timer. 2. suspend mode while a MB ball save timer
# is running and then resume when the MB timer expires. Remove redundancy of code between
# This mode and base with regard to shots, timers.
mode:
  priority: 2500 # range 100-1M
  start_events:
    - double_left_ramp_hit
    - bottom_lane_group_hit_complete    #Completed all lanes award both ball saves
  stop_events:
    - ball_ended
    - ball_save_banked_left_saving_ball
    - timer_left_bs_expiration_complete

ball_saves:
  #The ball save is enabled by mode starting. The timer starts
  #When the outlane roll over shot is hit. 100ms later
  #this mode's timer left_bs_lane_triggered completes and triggers
  #the ball save before the trough receives the ball.
  banked_left:
    enable_events: mode_banked_l_bs_started
    timer_start_events: left_outlane_banked_ballsave_hit
    early_ball_save_events:
      - timer_left_bs_lane_triggered_complete
    auto_launch: yes
    active_time: 1s
    hurry_up_time: 0s
    grace_period: 0s
    balls_to_save: 1
    source_playfield: earth_pf
    debug: no



timers:
  left_bs_expiration:
    start_value: 4
    end_value: 0
    direction: down
    tick_interval: 15s
    control_events:
      - event: mode_banked_l_bs_started #ball_waiting_to_eject_from_scoop_done
        action: restart #reset to starting value and start
      - event: banked_l_ballsave_double_left_ramp_hit{device.timers.left_bs_expiration.ticks<6}
        action: add
        value: 2
      - event: bottom_lane_group_hit_complete #Give a time bonus if the mode is already running.
        action: add
        value: 2
  left_bs_lane_triggered:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 100ms
    control_events:
      - event: left_outlane_banked_ballsave_hit
        action: restart

shots:
  left_outlane_banked_ballsave:  # Shot is used to enable bs rather than switch so bs can be deactivated during mb
    playfield: earth_pf
    disable_events:
      - multiball_poseidon_ramp_started
      - multiball_olympus_ramp_started  #add hidden hole mb when written
    enable_events: #Maybe enable when the mb ball saves are ended instead so the outlane bs can keep it going?
      - mode_banked_l_bs_started
      - multiball_poseidon_ramp_ended #re-enable when a mb ends.  This should not start the mode if not already running.
      - multiball_olympus_ramp_ended  #add hidden hole mb when written
    switches:
      - s_left_outlane
  banked_l_ballsave_double_left_ramp: #used to add time to banked ball save mode
    playfield: earth_pf
    profile: off_on
    enable_events:
      - left_ramp_hit #timer_base_left_ramp_tick{device.timers.base_left_ramp.ticks==6}
    disable_events:
      - timer_base_left_ramp_complete
    hit_events:
      - left_ramp_hit


show_player:
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks>5}:
    show_left_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6: #Start the beginning show
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==5}:
    show_left_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_5: #Start the beginning show
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==4}:
    show_left_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_4: #Start the beginning show
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==3}:
    show_left_shoulder_1:
      action: stop
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_3:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==2}:
    show_left_shoulder_1:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_2:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==1}:
    show_left_shoulder_2:
      action: stop
    show_left_shoulder_3:
      action: stop
    show_left_shoulder_4:
      action: stop
    show_left_shoulder_5:
      action: stop
    show_left_shoulder_6:
      action: stop
    show_left_shoulder_1:
      speed: 10
      action: play
  timer_left_bs_expiration_tick{device.timers.left_bs_expiration.ticks==0}:
    show_left_shoulder_1:
      action: stop

sound_player:
  mode_banked_l_bs_started: comboballsavelocked
  banked_l_ballsave_double_left_ramp_hit{device.timers.left_bs_expiration.ticks<6}: timeadded
