  base_hestia:
    events:
      - logicblock_field_all_pops_complete
    events_when_complete:
      - goddess_completed #Used for bonus mode
      - base_hestia_summoned #Note: logicblock_name_complete does not fire if there is an entry here.
    persist_state: true
    reset_on_complete: false
    reset_events:
      - multiball_goddess_ended
  base_demeter:
    events:
      - base_hestia_summoned
      - logicblock_field_all_pops_complete
    events_when_complete:
      - goddess_completed #Used for bonus mode
      - base_demeter_summoned #Note: logicblock_name_complete does not fire if there is an entry here.
    persist_state: true
    reset_on_complete: false
    reset_events:
      - multiball_goddess_ended
  base_hera:
    events:
      - base_hestia_summoned
      - base_demeter_summoned
      - logicblock_field_all_pops_complete
    events_when_complete:
      - goddess_completed #Used for bonus mode
      - base_hera_summoned #Note: logicblock_name_complete does not fire if there is an entry here.
    persist_state: true
    reset_on_complete: false
    reset_events:
      - multiball_goddess_ended
  base_hecate:
    events:
      - base_hestia_summoned
      - base_demeter_summoned
      - base_hera_summoned
      - logicblock_field_all_pops_complete
    events_when_complete:
      - goddess_completed #Used for bonus mode
      - base_hecate_summoned #Note: logicblock_name_complete does not fire if there is an entry here.
    persist_state: true
    reset_on_complete: false
    reset_events:
      - multiball_goddess_ended
  base_artimus:
    events:
      - base_hestia_summoned
      - base_demeter_summoned
      - base_hera_summoned
      - base_hecate_summoned
      - logicblock_field_all_pops_complete
    events_when_complete:
      - goddess_completed #Used for bonus mode
      - base_artimus_summoned #Note: logicblock_name_complete does not fire if there is an entry here.
    persist_state: true
    reset_on_complete: false
    reset_events:
      - multiball_goddess_ended
  base_athena:
    events:
      - base_hestia_summoned
      - base_demeter_summoned
      - base_hera_summoned
      - base_hecate_summoned
      - base_artimus_summoned
      - logicblock_field_all_pops_complete
    events_when_complete:
      - goddess_completed #Used for bonus mode
      - base_athena_summoned
    persist_state: true
    reset_on_complete: false
    reset_events:
      - multiball_goddess_ended
  base_aphrodite:
    events:
      - base_hestia_summoned
      - base_demeter_summoned
      - base_hera_summoned
      - base_hecate_summoned
      - base_artimus_summoned
      - base_athena_summoned
      - logicblock_field_all_pops_complete
    events_when_complete:
      - goddess_completed #Used for bonus mode
      - base_aphrodite_summoned
    persist_state: true
    reset_on_complete: false
    reset_events:
      - multiball_goddess_ended
