#config_version=5
#goddess mb mode
#Enter mode from completion of all goddesses. This can only happen when field
#is running. When mode starts, field ends. Activate lock with an orbit shot.
#Locking engaged enables post to send ball downstairs
#BB is locked up. Goddesses enter via holes.
#Final forth ball entering hole triggers the MB
#Hits to the holes are jackpots.
#Sequences to the pops increase the multiplier. (Light 2x 3x accordingly)
#If ball drains when locking, next ball resumes the mission.
# Add arrows and arrow shows`
# fix doubled up text
#
# figure out why ball gets stuck in scoop
mode:
  priority: 800
  start_events:
    - base_athena_summoned # {device.ball_devices.bd_poseidon_ramp.balls==0 and device.ball_devices.bd_olympus_ramp.balls==0}
    - key_c_pressed
  stop_events:
    - multiball_goddess_ended
  restart_on_next_ball: true #alternatively might need a start event for a ball being present in the lock

variable_player:
  multiball_lock_subway_lock_locked_ball:
    score: 5000
  logicblock_goddess_all_pops_complete:
    score: 20000

counters:
  goddess_multiplier:
    starting_count: 1
    persist_state: false
    count_events: logicblock_goddess_all_pops_complete

multiball_locks:
  subway_lock:
    source_playfield: earth_pf
    enable_events:
      - base_orbit_clockwise_hit
      - base_orbit_counter_clockwise_hit
    disable_events: multiball_lock_subway_lock_locked_ball
    balls_to_lock: 3
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_scoop
    balls_to_replace: 3 #2 #1=replace first ball locked from trough, use when triggering with lock full event.Default -1 = replace every ball locked with new ball
    debug: True

multiballs:
  goddess:
    source_playfield: earth_pf
    ball_count: 3
    ball_locks: bd_scoop
    ball_count_type: add  # increase number of playfield balls by couny
    shoot_again: 12s #ball save for MB 10 sec is default
    start_events: timer_goddesses_plotting_complete
    enable_events: mode_goddess_mb_starting
    debug: true

shots:
  goddess_trigger_mb_release:
    enable_events: multiball_lock_subway_lock_full
    disable_events: multiball_goddess_started
    playfield: earth_pf
    hit_events:
      - base_hole_distal_hit
      - base_hole_proximal_hit
    switches: s_ballblock


accruals:
  goddess_all_pops:
    events:
      - base_left_side_pop_hit
      - base_poseidon_pop_hit
#      - base_olympus_left_pop_hit
      - base_olympus_right_pop_hit
      - base_olympus_lower_pop_hit
    reset_on_complete: true


show_player:
#  mode_mystery_stopping: #dont start the ball timer until after ball hold ends
#    show_rainbow_all_but_bs:
#      speed: 2
  multiball_goddess_started:
    show_countdown99_green:
      speed: 10
      loops: 0
    show_everything_green:
      speed: 1
      loops: -1
    show_sparkle_gg_green:
      speed: 40
      loops: -1
#event_player:
#  mode_scoop_mb_started:
#    - force_bb_down
#  mode_scoop_mb_ending:
#    - release_bb_override

timers:
  goddesses_plotting:
    start_value: 1
    end_value: 0
    tick_interval: 3s
    direction: down
    control_events:
      - action: restart
        event: goddess_trigger_mb_release_hit

widgets:
  goddess_mb_shoot_orbits:
  - type: text
    text: "Loop Orbit to\nOpen Underworld"
    font_size: 60
    y: 75%
    x: 50%
    color: green
    font_name: GreekGods2
  goddess_mb_shoot_cave:
  - type: text
    text: "Shoot cave for\nRebellion"
    font_size: 60
    y: 75%
    x: 50%
    color: green
    font_name: GreekGods2
  goddess_mb_jackpot:
  - type: text
    text: Pop Sequence Jackpot!
    font_name: GreekGods2
    color: green
    y: 25%
    anchor_x: center
    anchor_y: center
    font_size: 75
    expire: 3s
  goddess_mb_bonus_instructions:
  - type: text
    text: "Hit All Pops\nFor Bonus"
    font_name: GreekGods2
    color: green
    y: 75%
    anchor_x: center
    anchor_y: center
    font_size: 75
    expire: 3s
  goddess_hestia:
  - type: text
    text: "Help Hestia\nTo the Underworld"
    font_name: GreekGods2
    color: green
    y: 25%
    anchor_x: center
    anchor_y: center
    font_size: 75
  goddess_artimus:
  - type: text
    text: "Help Artimus\nTo the Underworld"
    font_name: GreekGods2
    color: green
    y: 25%
    anchor_x: center
    anchor_y: center
    font_size: 75
  goddess_aphrodite:
  - type: text
    text: "Help Aphrodite\nTo in Underworld"
    font_name: GreekGods2
    color: green
    y: 25%
    anchor_x: center
    anchor_y: center
    font_size: 75
  goddess_athena:
  - type: text
    text: "Help Athena\nTo the Underworld"
    font_name: GreekGods2
    color: green
    y: 25%
    anchor_x: center
    anchor_y: center
    font_size: 75
#Order hestia artimus aphrodite athena
widget_player:
  slide_pf_goddess_mb_gather_instructions_slide_active:
    goddess_hestia:
      slide: pf_goddess_mb_gather_instructions_slide
    goddess_mb_shoot_orbits:
      slide: pf_goddess_mb_gather_instructions_slide
  base_orbit_clockwise_hit:
    goddess_mb_shoot_orbits:
      action: remove
  base_orbit_counter_clockwise_hit:
    goddess_mb_shoot_orbits:
      action: remove
  multiball_lock_subway_lock_locked_ball{device.ball_devices.bd_scoop.balls==1}:
    goddess_mb_shoot_orbits:
      slide: pf_goddess_mb_gather_instructions_slide
    goddess_hestia:
      action: remove
    goddess_artimus:
      slide: pf_goddess_mb_gather_instructions_slide
  multiball_lock_subway_lock_locked_ball{device.ball_devices.bd_scoop.balls==2}:
    goddess_mb_shoot_orbits:
      slide: pf_goddess_mb_gather_instructions_slide
    goddess_artimus:
      action: remove
    goddess_aphrodite:
      slide: pf_goddess_mb_gather_instructions_slide
  multiball_lock_subway_lock_locked_ball{device.ball_devices.bd_scoop.balls==3}:
    goddess_aphridite:
      action: remove
    goddess_athena:
      slide: pf_goddess_mb_gather_instructions_slide
    goddess_mb_shoot_cave:
      slide: pf_goddess_mb_gather_instructions_slide

slide_player:
  mode_goddess_mb_started:
    pf_goddess_mb_gather_instructions_slide:
      target: playfield_lcd
      background_color: 000000
      widgets:
      - type: text
        text: "Godesses to\nThe Underworld!"
        font_name: GreekGods2
        color: green
        y: 50%
        anchor_x: center
        anchor_y: center
        font_size: 45
  multiball_goddess_started:
    pf_goddess_mb_gather_instructions_slide:
      action: remove
    pf_goddess_mb_started_slide:
      target: playfield_lcd
      background_color: 000000
      widgets:
      - type: text
        text: "Goddess Rebellion!\nHit Caves for Bonus\nHit Pop Sequence for\nBonus Multiplier"
        font_name: GreekGods2
        color: green
        y: 50%
        anchor_x: center
        anchor_y: center
        font_size: 45

sound_player:
  multiball_lock_subway_lock_locked_ball{device.ball_devices.bd_scoop.balls==1}: v_ball_1_locked
  multiball_lock_subway_lock_locked_ball{device.ball_devices.bd_scoop.balls==2}: v_ball_2_locked
  multiball_lock_subway_lock_locked_ball{device.ball_devices.bd_scoop.balls==3}: v_ball_3_locked
  goddess_trigger_mb_release_hit: v_ball_4_locked
