#config_version=5
# This mode starts when both ramp locks are full. It then diverts the servo to middle, and watches
# for a ramp opto hit which then triggers both MB to activate and then diverts the servo to left ramp
#Would be better if the show player did not start until a mb was hit. Will have to modify sweep acordinly
mode:
  priority: 1900 # rides above both other mb
  start_events:
    - multiball_lock_poseidon_lock_full{device.ball_devices.bd_olympus_ramp.balls==2}
    - multiball_lock_olympus_lock_full{device.ball_devices.bd_poseidon_ramp.balls==2}
  stop_events:
    - mode_field_started # previously when field started
#    - multiball_poseidon_ramp_ended
#    - multiball_olympus_ramp_ended
event_player:
  mode_double_ramp_mb_started: ramp_servo_middle
  s_ramp_opto_active: start_double_mb #Start the mb for a ramp hit
  base_scoop_from_pf_hit: start_double_mb #4/21/22
  mode_poseidon_ramp_mb_started: ramp_servo_divert_left #Pick up which ever one posts first.
  mode_olympus_ramp_mb_started: ramp_servo_divert_left

show_player:
  #Things to do when double multiball started
#In sweep test to see if this mode is running multiball_olympus_ramp_started{}
  start_double_mb:
    show_sparkle_gg_white:
      speed: 40
    show_everything_white:
      loops: -1 #speed: 1
    show_countdown99_white:
      speed: 10
      loops: 0
