#config_version=5
# This mode starts when both ramp locks are full. It then diverts the servo to middle, and watches
# for a ramp opto hit which then triggers both MB to activate and then diverts the servo to left ramp
mode:
  priority: 11000 # range 100-1M
  start_events:
    - multiball_lock_poseidon_lock_full{device.ball_devices.bd_olympus_ramp.balls==2}
    - multiball_lock_olympus_lock_full{device.ball_devices.bd_poseidon_ramp.balls==2}
  stop_events:
    - mode_servo_starting #starts when both MB ended

event_player:
  mode_double_ramp_mb: ramp_servo_middle
  s_ramp_opto_active: start_double_mb #Start the mb for a ramp hit
  mode_poseidon_ramp_mb_started: ramp_servo_divert_left #Pick up which ever one posts first.
  mode_olympus_ramp_mb_started: ramp_servo_divert_left
