#config_version=5
# From 19 May 2019 machine
mode_settings:
  display_delay_ms: 1400ms
  hurry_up_delay_ms: 0
  hurry_up_event: flipper_cancel
  bonus_entries:
    - event: bonus_overdrive
      score: (device.counters.base_poseidon_overdrive.value + device.counters.base_olympus_overdrive.value) * 200
      skip_if_zero: false
    - event: bonus_sis
      score: device.counters.base_sis_completion.value * 750
      skip_if_zero: false
    - event: bonus_ballsaves
      score: device.counters.base_unused_ballsaves.value * 1000
      skip_if_zero: false
#    - event: bonus_math
#      score: 1000 * (current_player.some_variable + 2)
#  end_bonus_event: extra_ball_earned, extra_ball_not_earned

#event_player:
#  mode_bonus_starting: enter_hades_from_bonus_mode  -better to just pick up the mode_bonus_starting even in hades

slide_player:
   mode_bonus_started:
     bonus_start_slide:
       action: play
       target: score_lcd
     hades_face:
       action: play
       target: playfield_lcd
#   bonus_pops: bonus_pop_slide

widget_player:
   bonus_overdrive:
     bonus_overdrive_widget:
       action: add
       target: score_lcd
   bonus_sis:
     bonus_sis_widget:
       action: add
       target: score_lcd
   bonus_ballsaves:
     bonus_ballsaves_widget:
       action: add
       target: score_lcd
   bonus_total:
     bonus_total_widget:
       action: add
       target: score_lcd

widgets:
  bonus_overdrive_widget:
    - type: text
      text: (score)
      y: 65%
      x: 80%
      font_size: 100
      anchor_x: left
      anchor_y: center
  bonus_sis_widget:
    - type: text
      text: (score)
      y: 50%
      x: 80%
      font_size: 100
      anchor_x: left
      anchor_y: center
  bonus_ballsaves_widget:
    - type: text
      text: (score)
      y: 35%
      x: 80%
      font_size: 100
      anchor_x: left
      anchor_y: center
  bonus_total_widget:
    - type: text
      text: (score)
      y: 15%
      x: 80%
      font_size: 160
      anchor_x: left
      anchor_y: center

slides:
  hades_face:
    target: playfield_lcd
    widgets:
    - type: image
      image: hadesface2
      scale: 2
      y: 60%
    transition:
      type: fade
      duration: 1s

  bonus_start_slide:
    target: score_lcd  ##### might have to remove this if widget player does not place them on correct screen
    widgets:
    - type: image
      image: bonus_background
      z: -1
    - type: text
      text: Bonus
      y: 90%
      x: 50%
      font_size: 250
      anchor_x: center
      anchor_y: center
    - type: text
      text: "Super Qualifying Pop Hits x 200"
      y: 65%
      x: 10%
      font_size: 100
      anchor_x: left
      anchor_y: center
#    - type: text
#      text: "Ramps "
#      y: 70%
#      x: 40%
#      font_size: 100
#      anchor_x: left
#      anchor_y: center
    - type: text
      text: "Sisiphus Powerball Arcs x 750"
      y: 50%
      x: 10%
      font_size: 100
      anchor_x: left
      anchor_y: center
    - type: text
      text: "Unused Outlane Ball Protection x 1000"
      y: 35%
      x: 10%
      font_size: 100
      anchor_x: left
      anchor_y: center
    - type: text
      text: "Total Bonus"
      y: 20%
      x: 10%
      font_size: 160
      anchor_x: left
      anchor_y: center


#sound_player:
#  mode_bonus_started: snd_bonus_riff3
