#config_version=5
# This mode runs the servo in response to config's state machine's posted events. This mode runs all the time.
# diverter is defined in hardware with control events ramp_servo_divert_left (or right).
# 5/24/21 added switch s_diverter_midpoint. Switch activates as diverter arc starts and inactivates near arc completion. If switch does
# not inactivate it probably means a ball got pinched. A timer is started every time state machine commands the diverter to move to one side
# The timer is aborted when the mid point switch inactivates.  If the timer makes it down to 0 show player starts a show which reverses
# the arc, displays an error message and then commands the diverter to reverse directions and then bring it back to the target position.
# This is a one time correction. If it fails -> smoke.
# 5/27/21: Ripped out old ramp_flap_tracking state machine and made servo control dictated by state machine.
# Servo could be controlled diectly via state machine but I chose to relay it here for readability with mitigation steps.
# Bug, rapid wagging of servo as in state machine or other modes sending conflicting data will give a double wag and false alarm.
# Do: create some kind of counter that detects if a second jam occurs and shuts down game.
mode:
  priority: 10000 # range 100-1M
  start_events:
    - mode_base_started

event_player:
  #This might be better dealt with using a diverter construct http://docs.missionpinball.org/en/dev/mechs/diverters/servo_as_diverter.html
  ramp_flap_control_move_divert_left: ramp_servo_divert_left
  ramp_flap_control_move_divert_right: ramp_servo_divert_right
  ramp_flap_control_move_middle: noted_by_mode_servo_but_processed_in_hardware

timers:
  moving_left:
    start_value: 2
    end_value: 0
    tick_interval: 250 ms
    direction: down
    control_events:
      - event: ramp_flap_control_move_divert_left
        action: restart
      - event: s_diverter_midpoint_inactive
        action: stop
  moving_right:
    start_value: 2
    end_value: 0
    tick_interval: 250 ms
    direction: down
    control_events:
      - event: ramp_flap_control_move_divert_right
        action: restart
      - event: s_diverter_midpoint_inactive
        action: stop

show_player:
  timer_moving_left_complete: #Timer should never complete. If completed it means the flap did not complete its arc, probably a ball is stuck
    show_diverter_jammed_when_moving_left:
      speed: 1
      loops: 0
  timer_moving_right_complete: #Timer should never complete. If completed it means the flap did not complete its arc, probably a ball is stuck
    show_diverter_jammed_when_moving_right:
      speed: 1
      loops: 0
