#config_version=5
# This mode runs the servo when the one ball game is running. I spun this into its own mode I can stop the servo from running
# during MB so a sis hit does not pinch a ball on the ramp or trap the ball on a bounce off the post. Servo control is also
# run by the modes p_ramb_mb and o_ramp_mb.
# 5/24/21 added switch s_diverter_midpoint. Switch activates as arc starts and inactivates near arc completion. If switch does
# not inactivate it probably means a ball got pinched. Every time a divert is commanded a timer is started. The timer stops when
# the switch becomes inactive. If the timer makes it down to 0 show player starts a show which reverses the arc, displays an error
# message and attempts to bring the arc back to the target position.
# Do: Make a counter that counts the retries and crashes the game if > 2 retries.
# Do: Move servo control out of p_ramp_mb and o_ramp_mb and back in here so ball jamming gets detected. (Better check to be sure no servo control in state machines first)
mode:
  priority: 10000 # range 100-1M
  start_events:
    - mode_base_started{device.ball_devices.bd_poseidon_ramp.balls<2 and device.ball_devices.bd_olympus_ramp.balls<2}
    - multiball_poseidon_ramp_ended
    - multiball_olympus_ramp_ended
  stop_events:
    - multiball_lock_poseidon_lock_full #Allow p_ramp_mb mode to controll servo until MB done
    - multiball_lock_olympus_lock_full #Allow p_ramp_mb mode to controll servo until MB done

event_player:
  #These should be handled in the sis lat and medial modes or possibly field
  mode_servo_started{device.switches.s_sis_left.state==1}: ramp_servo_divert_left #divert_left
  mode_servo_started{device.switches.s_sis_right.state==1}: ramp_servo_divert_right #divert_right
  #This might be better dealt with using a diverter construct http://docs.missionpinball.org/en/dev/mechs/diverters/servo_as_diverter.html
  base_sis_left_arrived_hit: ramp_servo_divert_left #divert_left
  base_sis_right_arrived_hit: ramp_servo_divert_right #divert_right

timers:
  moving_left:
    start_value: 6
    end_value: 0
    tick_interval: 250 ms
    direction: down
    control_events:
      - event: ramp_servo_divert_left
        action: restart
      - event: s_diverter_midpoint_inactive
        action: stop
  moving_right:
    start_value: 6
    end_value: 0
    tick_interval: 250 ms
    direction: down
    control_events:
      - event: ramp_servo_divert_right
        action: restart
      - event: s_diverter_midpoint_inactive
        action: stop

show_player:
  timer_moving_left_complete: #Timer should never complete. If completed it means the flap did not complete its arc, probably a ball is stuck
    show_diverter_jammed_when_moving_left:
      speed: 1
      loops: 0
  timer_moving_right_complete: #Timer should never complete. If completed it means the flap did not complete its arc, probably a ball is stuck
    show_diverter_jammed_when_moving_right:
      speed: 1
      loops: 0
