#config_version=5
# This mode activates with o_locking_elgible. It then it calls for the lock to lite via
# a hit to the ball_block target. After this the player locks a ball and mode quits. Second time
# through it locks a ball as before and then while still active calls for the MB start at the scoop.
# If the ball drains before the ball is locked, this mode starts when field starts because
# accrual base_o_locking_engaged.completed==True
# widget prompts to the player and light shows are handled in this mode.
# After the lock is full the state machine sends the ramp servo to the other lock until after MB is
# finished or until P lock is full in which case the diverter points to the middle
# and then a shot to the BB or ramp starts double MB.
#10-17-21 added accrual device.accruals.base_o_locking_engaged to track if light lock shot already hit
#so mode wont require this on restart if ball drains before ball locked. Internal to this mode is an
#equivelent accrual that manages screen messages and widgets. It might be possible to just use the base one
mode:
  priority: 1500 # range 100-1M
  start_events:
    - o_locking_elgible
    - mode_field_started{device.ball_devices.bd_olympus_ramp.balls==2} #Lock is full, calling for scoop shot
    - mode_field_started{device.accruals.base_o_locking_engaged.completed} # #==True} #completed means that o_locking_elgible has not been reset by a locked ball. Starts the mode if the mode is qualified on prior ball
  stop_events:
    - multiball_olympus_ramp_ended
    - kill_o_locking #Used by mystery award to switch lock to other side because sis on wrong side.
    - multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 1}
    - mode_goddess_mb_started #When field restarts this mode should re-spawn if engaged completed
    - mode_hydra_started #When field restarts this mode should re-spawn if engaged completed
multiball_locks:
  olympus_lock:
    source_playfield: earth_pf
    enable_events:
      - ormb_light_o_lock_hit
      - mode_o_ramp_mb_started{device.accruals.base_light_o_lock_already_hit.completed}
    disable_events:
      - multiball_olympus_ramp_started
      - multiball_lock_olympus_lock_locked_ball
    balls_to_lock: 2
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_olympus_ramp
    balls_to_replace: 2 #2 #1=replace first ball locked from trough, use when triggering with lock full event.Default -1 = replace every ball locked with new ball
    debug: True

multiballs:
  olympus_ramp:
    source_playfield: earth_pf
    ball_count: 2
    ball_count_type:   add #total increase number of playfield balls to count
    ball_locks: bd_olympus_ramp
    replace_balls_in_play: false #true # false leaves one in the lock see http://docs.missionpinball.org/en/latest/game_logic/multiballs/multiball_with_traditional_ball_lock.html
    enable_events:
      - mode_o_ramp_mb_started
    disable_events:
      - multiball_olympus_ramp_ended
    start_events:
      - ormb_start_shot_hit   #####Probably here is my problem starting both mb without other lock full
      - prmb_start_shot_hit
      - balldevice_bd_olympus_ramp_ball_missing #Experimental fix for a ball that slipped through the lock 11/21/20
      - start_double_mb #Picks up a ramp opto hit broadcast from double_ramp_mb mode
    shoot_again: 10s #default ball save is 10 sec
    debug: true

shot_profiles:
  flashing_off_o:
    advance_on_hit: false
    loop: false
    states:
      - name: flashing
        show: flash
        speed: 3
      - name: off
        show: off

shots:
  ormb_light_o_lock:
    playfield: earth_pf
    profile: flashing_off_o
    enable_events:
      - mode_o_ramp_mb_started{device.ball_devices.bd_olympus_ramp.balls<2} # and not logicblock_base_light_o_lock_already_hit.completed} #This enables the shot when mode starts provide lock is not already full.
    reset_events: multiball_lock_olympus_lock_locked_ball
    disable_events: ormb_light_o_lock_hit
    hit_events:
      - ball_block_hit
    debug: true
  ormb_start_shot:
    playfield: earth_pf
    profile: flashing_off_o
    enable_events:
      - multiball_lock_olympus_lock_full
      - mode_o_ramp_mb_started{device.ball_devices.bd_olympus_ramp.balls==2}
    disable_events: ormb_start_shot_hit
    hit_events: base_scoop_from_pf_hit
    debug: true
  ormb_jackpot:
    playfield: earth_pf
    profile: flashing_off_o
    enable_events: multiball_olympus_ramp_started
    hit_events: base_hole_proximal_hit
    debug: true
    persist_enable: false

variable_player:
  ormb_jackpot_hit:
    score: 5000

timers:
  ormb_allow_ball_block_to_settle: # used to allow ball block to register hit and activate timer in mode_scoop so timer can be paused. Replace this timer with show when appropriate
    #This timer was used when the scoop shot activated the multiball.  But this presented a problem for qualifying the other ramp's locks and was removed.
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: multiball_lock_olympus_lock_full
        action: restart #reset to starting value and start

event_player:
  timer_ormb_allow_ball_block_to_settle_complete: pause_ball_block_timer # invite scoop shot
#  ormb_light_o_lock_hit: jump_ball_block_timer_to_1 #Raise the BB fast by jumping timer to 1
  olympus_mech_hit: bonus_pop #used by counter in base for bonus calculation
#  multiball_lock_olympus_lock_full: force_bb_down
#  multiball_olympus_ramp_started: release_bb_override

show_player:
  #Things to do when starting
  mode_o_ramp_mb_started{device.ball_devices.bd_olympus_ramp.balls<2 and not device.accruals.base_light_o_lock_already_hit.completed}: #  mode_o_ramp_mb_started{device.ball_devices.bd_olympus_ramp.balls==0}:
    show_attention_ball_block:
      speed: 4
      sync_ms: 250
      show_tokens:
        color1: yellow
        color2: stop
  mode_o_ramp_mb_started{device.ball_devices.bd_olympus_ramp.balls==2}:
    show_attention_scoop:
      speed: 8
      show_tokens:
        color1: yellow
        color2: black
  #Things to do when enable the lock shot hit
  ormb_light_o_lock_hit: #player has hit qualifying shot Here is where the locks are lit and arrow directs player to shoot ramp
    show_attention_ball_block:
      action: stop
    show_swirl_right_spk_yellow:
      speed: 10
    show_o_ramp_mb_0_balls:
      speed: 20
  ormb_light_o_lock_hit{device.state_machines.ramp_flap_control.state=="divert_right"}: #diverter is on correct side to lock ball
    show_flash_ramp_arrow:
      speed: 4
      show_tokens:
        color: yellow
  #Things to do when diverter moves
  ramp_flap_control_move_divert_left{device.multiball_locks.olympus_lock.enabled}: #Diverter moved to other side
    show_flash_ramp_arrow:
      action: stop
  ramp_flap_control_move_divert_right{device.multiball_locks.olympus_lock.enabled}: #Diverter moded back to correct side for locking ball
    show_flash_ramp_arrow:
      speed: 4
      show_tokens:
        color: yellow
  #Things to do when lock is full
  multiball_lock_olympus_lock_full:
    show_attention_scoop:
      speed: 8
      show_tokens:
        color1: yellow
        color2: black
#  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 2}:
    show_flash_ramp_arrow:
      action: stop
    show_o_ramp_mb_1_balls:
      action: stop
    show_o_ramp_mb_2_balls:
      speed: 20
  #Things to do when multiball started
  multiball_olympus_ramp_started:
    show_attention_scoop:
      action: stop
    show_sparkle_gg_yellow:
      speed: 40
    show_everything_yellow:
      loops: -1 #speed: 1
    show_swirl_right_spk_yellow:
      action: stop
    show_o_ramp_mb_2_balls:
      action: stop
    show_countdown99_yellow:
      speed: 10
      loops: 0
    show_malstrom_spin_ccw_yellow:
      speed: 8
  #Things to do when shutting down either from ball loss, first ball locked or MB ended
  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 1}:
    show_flash_ramp_arrow:
      action: stop
    show_o_ramp_mb_0_balls:
      action: stop
    show_o_ramp_mb_1_balls:
      speed: 20



widgets:
  shoot_scoop_target_yellow:
    - type: text
      text: SHOOT  SCOOP  TARGET
      font_name: greekgods3
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: ff8c00
      z: 5
      events_when_added: yellow_message_added_to_slide_show_progress_to_ramp_mb
  shoot_scoop_yellow:
    - type: text
      text: SHOOT  THE  SCOOP
      font_name: greekgods3
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: ff8c00
      z: 5
      events_when_added: yellow_message_added_to_slide_show_progress_to_ramp_mb
  qualified_yellow:
    - type: text
      text: "Q\nU\nA\nL\nI\nF\nI\nE\nD"
      font_name: greekgods3
      color: green
      font_size: 58
      x: 630
      y: 160
      anchor_x: center
      anchor_y: bottom
      rotation: 0
      z: 5
  shoot_ramp_yellow:
    - type: text
      text: SHOOT  THE  RAMP
      font_name: greekgods3
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: ff8c00
      z: 5
      events_when_added: yellow_message_added_to_slide_show_progress_to_ramp_mb
  move_sis_yellow:
    - type: text
      text: ROLL  BOULDER  TO  OTHER  SIDE
      font_name: greekgods3
      font_size: 36
      x: 384
      y: 53
      anchor_x: center
      anchor_y: bottom
      color: ff8c00
      z: 5
  announce_mb_pf:
    - type: image
      image: mb_3balls
      scale: 0.44
      anchor_x: center
      anchor_y: center
      x: 384
      y: 455
      z: 2
      animations:
        add_to_slide:
          - property: rotation
            value: 0
            relative: false
            duration: 0
          - property: rotation
            value: 360
            relative: false
            duration: 4s
            easing: linear #http://docs.missionpinball.org/en/latest/displays/widgets/easing.html
            repeat: true
  announce_mb_pf_mask:
    - type: image
      image: mb_mask
      scale: 0.5
      anchor_x: center
      anchor_y: bottom
      x: 394
      y: 155
      z: 1
  announce_yellow_jackpot:
    - type: image
      image: jackpot_yellow
      scale: 0.2
      anchor_x: center
      anchor_y: center
      x: 384
      y: 455
      z: 3
      animations:
        add_to_slide:
        - property: scale
          value: 1.2
          relative: false
          duration: 0.25
          easing: in_out_cubic
        - property: scale
          value: 0
          relative: false
          duration: 0.25
          easing: in_out_cubic

widget_player:
  #Things to do when starting
  mode_o_ramp_mb_started{device.ball_devices.bd_olympus_ramp.balls<2 and not device.accruals.base_light_o_lock_already_hit.completed}: #Mode started hasnt lit
    qualified_yellow:
      slide: show_progress_to_ramp_mb #Adds widget on top pillar of this slide which was posted in field
      action: add
    shoot_scoop_target_yellow:
      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
      action: add
    #Remove anything that may be in the way
    shoot_scoop_target_blue:
      action: remove
    shoot_ramp_blue:
      action: remove
  mode_o_ramp_mb_started{device.ball_devices.bd_olympus_ramp.balls<2 and device.accruals.base_light_o_lock_already_hit.completed}: #Mode started has lit and lock not full
    shoot_ramp_yellow:
      slide: show_progress_to_ramp_mb
      action: add
    #Remove anything that may be in the way
    shoot_scoop_target_blue:
      action: remove
    shoot_ramp_blue:
      action: remove
  mode_o_ramp_mb_started{device.ball_devices.bd_olympus_ramp.balls==2}: #Mode started and lock full
    shoot_scoop_yellow:
      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
      action: add
    #Remove anything that may be in the way
    shoot_scoop_target_blue:
      action: remove
    shoot_ramp_blue:
      action: remove
  #Things to do when enable the lock shot hit
  ormb_light_o_lock_hit: #clean up
    qualified_yellow:
      slide: show_progress_to_ramp_mb
      action: remove #show naked progress bar again for next qualify
    shoot_scoop_target_yellow:
      slide: show_progress_to_ramp_mb
      action: remove
    #Remove anything else that may be in the way
    shoot_scoop_target_blue:
      action: remove
    shoot_ramp_blue:
      action: remove
  ormb_light_o_lock_hit{device.state_machines.ramp_flap_control.state=="divert_right"}: #diverter is on correct side to lock ball
    shoot_ramp_yellow:
      slide: show_progress_to_ramp_mb
      action: add
  #Things to do when diverter moves
  ramp_flap_control_move_divert_left{device.multiball_locks.olympus_lock.enabled}: #Diverter moved to other side
    shoot_ramp_yellow:
      slide: show_progress_to_ramp_mb
      action: remove
    move_sis_yellow:
      slide: show_progress_to_ramp_mb
      action: add
      widget_settings:
        expire: 8 sec
  ramp_flap_control_move_divert_right{device.multiball_locks.olympus_lock.enabled}: #Diverter moded back to correct side for locking ball
    shoot_ramp_yellow:
      slide: show_progress_to_ramp_mb
      action: add
    move_sis_yellow:
      slide: show_progress_to_ramp_mb
      action: remove
    #Remove anything else that may be in the way
    shoot_scoop_target_blue:
      action: remove
    shoot_ramp_blue:
      action: remove
  #Things to do when lock is full
  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 2}:
    shoot_ramp_yellow:
      slide: show_progress_to_ramp_mb
      action: remove
    shoot_scoop_yellow:
      slide: show_progress_to_ramp_mb
      action: add
    #Remove anything else that may be in the way
    shoot_scoop_target_blue:
      action: remove
    shoot_ramp_blue:
      action: remove
  #Things to do when multiball started
  multiball_olympus_ramp_started:
    shoot_scoop_yellow:
      slide: show_progress_to_ramp_mb
      action: remove
    announce_mb_pf:
      slide: show_progress_to_ramp_mb
      action: add
    announce_mb_pf_mask:
      slide: show_progress_to_ramp_mb
      action: add
  #Things to do when shutting down either from ball loss, first ball locked or MB ended
  mode_o_ramp_mb_ending:
    move_sis_yellow:
      action: remove
    shoot_scoop_target_yellow:
      action: remove
    shoot_ramp_yellow:
      action: remove
    announce_mb_pf:
      action: remove
    announce_mb_pf_mask:
      action: remove
  #Things to do when p_ramp_mb adds a widget
  #This is a hack to prevent competing messages to show at the same time.  A better long term
  #solution may be to put a mask behind each text widget that is added and removed with the
  #text allowing the messages to be layered.  This may not z correctly however and both modes
  #might have to be given the same Z or somehow the ramp mb's added into the same mode.
  blue_message_added_to_slide_show_progress_to_ramp_mb: #pull off yellow messages so they dont compete with updated blue one
    shoot_scoop_yellow:
      slide: show_progress_to_ramp_mb
      action: remove
    shoot_ramp_yellow:
      slide: show_progress_to_ramp_mb
      action: remove
  ormb_jackpot_hit:
    announce_yellow_jackpot:
      target: playfield_lcd
      action: add
      widget_settings:
        expire: 0.5 sec

slide_player:
  left_ramp_hit{device.multiball_locks.olympus_lock.enabled}:
    move_boulder_2r:
      target: playfield_lcd
      expire: 3.3s
      widgets:
      - type: image
        image: sisl2r
        fps: 30
        scale: 0.5
        y: 65%
        z: 5000
      - type: text
        text: ROLL  POWERBALL  TO  OTHER  SIDE
        font_name: greekgods3
        font_size: 36
        x: 384
        y: 53
        anchor_x: center
        anchor_y: bottom
        color: yellow

accruals:
  #This is designed to fire once to give instructions a single time during the game
  move_powerball_instructions_o:
    events:
      - left_ramp_hit{device.multiball_locks.olympus_lock.enabled}
    persist_state: true
    reset_on_complete: false
    disable_on_complete: true

sound_player:
  multiball_olympus_ramp_started: v_multiball
  multiball_lock_olympus_lock_full: v_shoot_scoop_mb #defigned in sounds in config
  ormb_jackpot_hit: v_jackpot
  mode_o_ramp_mb_started{not device.accruals.base_light_o_lock_already_hit.completed}: v_shoot_scoop_target_to_enable_lock
  mode_o_ramp_mb_started{device.state_machines.ramp_flap_control.state=="divert_right" and device.accruals.base_light_o_lock_already_hit.completed}:  v_shoot_ramp_to_lock_ball #diverter is on correct side to lock ball when mode starts and lock already lit
  ormb_light_o_lock_hit{device.state_machines.ramp_flap_control.state=="divert_right"}:  v_shoot_ramp_to_lock_ball #diverter is on correct side to lock ball
  ormb_light_o_lock_hit{device.state_machines.ramp_flap_control.state=="divert_left" and not mode.p_ramp_mb.active}: v_move_powerball_to_other_side_to_lock_ball #condition agains other mode running to decrease false alarms.
  logicblock_move_powerball_instructions_o_complete{not mode.p_ramp_mb.active}: v_move_powerball_to_other_side_to_lock_ball #Announces once if ramp hit with flap in wrong spot
  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 1 and device.multiball_locks.poseidon_lock.locked_balls == 0}: v_ball_1_locked
  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 2 and device.multiball_locks.poseidon_lock.locked_balls == 0}: v_ball_2_locked
  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 1 and device.multiball_locks.poseidon_lock.locked_balls == 1}: v_ball_2_locked
  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 2 and device.multiball_locks.poseidon_lock.locked_balls == 1}: v_ball_3_locked
  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 1 and device.multiball_locks.poseidon_lock.locked_balls == 2}: v_ball_3_locked
  multiball_lock_olympus_lock_locked_ball{device.multiball_locks.olympus_lock.locked_balls == 2 and device.multiball_locks.poseidon_lock.locked_balls == 2}: v_ball_4_locked
