#config_version=5
# This mode runs works similar to a simple state machine. I am unsing it over a state machine so it
# will show up on the mode running list.  When shots to the ball block drop target are invited by
# p_ramp_mb (light lock), o_ramp_mb(light lock), hydra_mb(start mode) this mode raises the ball block
# drop target. The drop also needs to be raised when a ball is starting and a lock or mode are qualified.
# Test: drop target behavior with two players.
#
# Incomplete editing. This mode can probably go away in favor of events in Hardware
#
mode:
  priority: 200 # range 100-1M
  start_events:
    - raise_bb
  stop_events:
    - release_bb_override
    - game_ending
  restart_on_next_ball: TRUE

coil_player:
  mode_bb_down_started:
    c_ball_block_fall:
      action: pulse
  ball_started{device.switches.s_ball_block.state==1}: #Drop the ball block target again if player is restarting in a multiplayer game
    c_ball_block_fall:
      action: pulse
