#config_version=5
# accelerate river c (right river, top to bottom)
# When ending timer handler_x starts an keeps the mode alive for two seconds so
# the mode code has time to shut down the accelerate rules. When the magnets
# should be triggering the river mouths flash. After each should be
# trigger, the accelerate rule is turned off for 2 seconds. This prevents
# the ball from getting trapped trying to exit upslope. It also prevents
# overheating.
# Consider having show player just blink the mouth at ball exit not the whole river.
mode:
  start_events:
    - accelerate_rivers
    - mode_hades_bug_game_starting
  stop_events: timer_handler_c_complete
  code: river_c_fast.river_c_fast
  priority: 6300 #Must be above hades' show player

event_player:
  mode_river_c_fast_started: accelerate_c|1s
  left_river_top_to_bottom_hit: normalize_c
  timer_cooldown_c_complete: accelerate_c
  mode_hades_bonus_game_stopped: normalize_c
  mode_hades_bug_game_stopped: normalize_c

timers:
  handler_c:
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 2s
    control_events:
      - action: restart
        event: mode_hades_bonus_game_stopped
      - action: restart
        event: mode_hades_bug_game_stopped
  cooldown_c:
    start_value: 2
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: restart
        event: right_river_top_to_bottom_hit

#show_player:
#  right_river_top_to_bottom_hit:
#    show_hades_right_mouths_red:
#      speed: 5
#      loops: 0
