#config_version=5

sound_system:  #http://docs.missionpinball.org/en/latest/sound/basic_setup.html?highlight=sound%20player
    frequency: 44100
    buffer: 512
    channels: 2
    master_volume: 1
    tracks:
       music:
          type: standard #sound_loop  Have to change it back to sound_loop if using them
          simultaneous_sounds: 1
          volume: 0.6
       loops:
          type: sound_loop #standard #sound_loop  Have to change it back to sound_loop if using them
          simultaneous_sounds: 1
          volume: 0.6
       voice:
          type: standard
          simultaneous_sounds: 1
          volume: 1
          ducking:
            target: loops
            delay: 50 ms
            attack: 50 ms
            attenuation: 0.66
            release_point: 1.2s #start releasing the ducking 100ms from end of callout
            release: 200 ms
       sfx:
          type: standard
          simultaneous_sounds: 4
          volume: 1
assets:
    sounds:
        default:
            load: preload #on_demand
        music:
            track: music
            load: preload #on_demand
        sfx:
            track: sfx
#            load: preload #on_demand
        voice:
            track: voice
#            load: preload #on_demand

sounds:
  slingshot:
    file: little_metal.ogg
    volume: 1
    max_queue_time: 0
    track: sfx
  snd_underworld_open:
    file: underworldopen.ogg
    track: sfx
  snd_bat1:
    file: bat1.ogg
    track: sfx
  snd_bat2:
    file: bat2.ogg
    track: sfx
  snd_bat3:
    file: bat3.ogg
    track: sfx
  snd_bat4:
    file: bat4.ogg
    track: sfx
  snd_hades_target:
    file: hades_target1.ogg
    track: sfx
  snd_left_main_ss:
    file: little_metal_left44k.ogg
#    volume: 1
    max_queue_time: 500ms
    track: sfx
  snd_right_main_ss:
    file: little_metal_right44k.ogg
#    volume: 1
    max_queue_time: 500ms
    track: sfx
  snd_ramp_1:
    file: ramp_1.ogg
    track: sfx
  snd_ramp_2:
    file: ramp_2.ogg
    track: sfx
  snd_poseidon_mech:
    file: little_metal_poseidon44k.ogg
    track: sfx
    max_queue_time: 500ms
  snd_olympus_mech:
    file: little_metal_olympus_pops44k.ogg
    track: sfx
    max_queue_time: 500ms
  snd_orbit:
    file: big_swoosh.ogg
    track: sfx
  snd_river:
    file: little_swoosh.ogg
    track: sfx
  snd_spinner:
    file: tiny_laser.ogg
    track: sfx
    max_queue_time: 500ms
  snd_drop_1:
    file: little_metal_dropdown1.ogg
    track: sfx
  snd_drop_2:
    file: little_metal_dropdown2.ogg
    track: sfx
  snd_drop_3:
    file: little_metal_dropdown3.ogg
    track: sfx
  snd_drop_up:
    file: little_metal_dropup.ogg
    track: sfx
  snd_scott_pop:
    file: little_metal_scottpop44k.ogg
    track: sfx
  snd_sis:
    file: medium_swoosh.ogg
    track: sfx
  snd_hydra:
    file: medium_metal.ogg
    track: sfx
  snd_shield:
    file: shield.ogg
    track: sfx
  snd_splat-and-crunch:
    file: splat-and-crunch.wav
    track: sfx
  snd_buzz:
    file: buzz.ogg
    track: sfx
#  snd_follow_bliss:
#    file: follow_bliss.ogg
#    track: music
  v_shoot_scoop_mb:
    file: cmgg2_shoot_scoop_for_mb.ogg
    volume: 1
    max_queue_time: 2s
    track: voice
  v_multiball:
    file: cmgg2_multiball.ogg
    volume: 1
    max_queue_time: 100ms
    track: voice
  #shootblinkingtarget:
  #  file: shoottheblinkingtarget.ogg
  #  volume: 1
  #  track: voice
  v_goddess_awarded:
    file: cmgg2_goddess_awarded.ogg
    volume: 1
    max_queue_time: 4s
    track: voice
  #v_ball_locked:
  #  file: balllocked.ogg
  #  volume: 0.8
  #  track: voice
  v_ball_1_locked:
    file: cmgg2_ball_1_locked.ogg
    volume: 1
    track: voice
  v_ball_2_locked:
    file: cmgg2_ball_2_locked.ogg
    volume: 1
    track: voice
  v_ball_3_locked:
    file: cmgg2_ball_3_locked.ogg
    volume: 1
    track: voice
  v_ball_4_locked:
    file: cmgg2_ball_4_locked.ogg
    volume: 1
    track: voice
  v_ball_saved:
    file: cmgg2_ball_saved.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
#  v_welcome:
#    file: cmgg2_welcome.ogg
#    volume: 1.75
#    track: voice
#  v_almost_there:
#    file: cmgg2_almost_there.ogg
#    volume: 1.5
#    track: voice
  v_combo:
    file: cmgg2_combo.ogg
    volume: 1.75
    track: voice
    max_queue_time: 2s
  v_outlane_bs_awarded:
    file: cmgg2_outlane_protection_awarded.wav
    volume: 1
    track: voice
    priority: 1
    max_queue_time: 5s

#  v_right_outlane_bs_awarded:
#    file: cmgg2_right_outlane_bs_awarded.ogg
#    volume: 1
#    track: voice
#    priority: 1
#    max_queue_time: 5s
#  v_left_outlane_bs_awarded:
#    file: cmgg2_left_outlane_bs_awarded.ogg
#    volume: 1
#    track: voice
#    priority: 0
#    max_queue_time: 5s
  v_move_powerball_to_other_side_to_lock_ball:
    file: cmgg2_move_powerball_to_other_side_to_lock_ball.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
  v_shoot_ramp_to_lock_ball:
    file: cmgg2_shoot_ramp_to_lock_ball.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
  v_complete_drop_targets_to_qualify_mystery_mode:
    file: cmgg2_complete_drop_targets_to_qualify_mystery_mode.ogg
    volume: 1
    track: voice
    max_queue_time: 5s
  v_hit_blinking_band_enable_mystery_award:
    file: cmgg2_hit_blinking_band_enable_mystery_award.ogg
    volume: 1
    track: voice
    max_queue_time: 4s
  v_shoot_orbit_hole_for_mystery_award:
    file: cmgg2_shoot_orbit_hole_for_mystery_award.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
#  v_double_outlane_bs_awarded:
#    file: cmgg2_double_outlane_bs_awarded.ogg
#    volume: 1
#    track: voice
#    priority: 2
#    max_queue_time: 2s
  v_time_added:
    file: cmgg2_time_added.ogg
    volume: 1.5
    track: voice
    priority: 3
    max_queue_time: 2s
  v_completed_lane_lights_award_bs:
    file: cmgg2_completed_lane_lights.wav
    volume: 1
    track: voice
    max_queue_time: 5s
  v_use_knee_switch:
    file: cmgg2_use_knee_switch.wav
    volume: 1
    track: voice
    max_queue_time: 3s
  v_poseidon_bonus_scoring:
    file: cmgg2_poseidon_bonus_scoring.wav
    volume: 1
    track: voice
    max_queue_time: 4s
  v_olympus_bonus_scoring:
    file: cmgg2_olympus_bonus_scoring.wav
    volume: 1
    track: voice
    max_queue_time: 4s
  v_extra_ball_awarded:
    file: cmgg2_extra_ball_awarded.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
  v_help_hades:
    file: cmgg2_help_hades.wav
    volume: 1
    track: voice
    max_queue_time: 2s
  v_roll_ball_hydra:
    file: cmgg2_roll_ball_hydra.wav
    volume: 1
    track: voice
    max_queue_time: 2s
  v_shoot_pops_shoot_holes:
    file: cmgg2_shoot_pops_shoot_holes.wav
    volume: 1
    track: voice
    max_queue_time: 2s
  v_shoot_orbit_open_underworld:
    file: cmgg2_shoot_orbit_open_underworld.wav
    volume: 1
    track: voice
    max_queue_time: 2s
  v_your_soul_stays:
    file: cmgg2_your_soul_stays.ogg
    volume: 1
    track: voice
    max_queue_time: 1s
  v_you_returned_underworld:
    file: cmgg2_you_returned_underworld.ogg
    volume: 1
    track: voice
    max_queue_time: 1s
  v_underworld_cleansed:
    file: cmgg2_the_underworld_is_cleansed.ogg
    volume: 1
    track: voice
  v_shoot_tunnels_bats:
    file: cmgg2_shoot_tunnels_bats.ogg
    volume: 1.2
    track: voice
    max_queue_time: 2s
  v_super_spinner_engaged:
    file: cmgg2_super_spinner_engaged.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
  v_hit_the_lower_pop_for_bonus:
    file: cmgg2_hit_the_lower_pop_for_bonus.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
  v_mystery_award:
    file: cmgg2_mystery_award.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
#  v_hit_all_pops_to_summon_goddess:
#    file: cmgg2_hit_all_pops_to_summon_goddess.ogg
#    volume: 1
#    track: voice
  v_ready_locks_by_scoring:
    file: cmgg2_ready_locks_by_scoring.ogg
    volume: 1
    track: voice
    max_queue_time: 5s
  v_shoot_ramp_twice_outlane_protection:
    file: cmgg2_shoot_ramp_again_for.wav
    volume: 1
    track: voice
    max_queue_time: 5s
  v_skill_shot_awarded:
    file: cmgg2_skill_shot_awarded.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
  v_super_skill_shot_awarded:
    file: cmgg2_super_skill_shot_awarded.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
  v_jackpot:
    file: cmgg2_jackpot.ogg
    volume: 1
    track: voice
    max_queue_time: 500 ms
  v_shoot_scoop_target_to_enable_lock:
    file: cmgg2_shoot_scoop_target_to_enable_lock.ogg
    volume: 1
    track: voice
    max_queue_time: 2s
  v_hydra_battle_victorious:
    file: cmgg2_hydra_battle_victorious.ogg
    volume: 1
    track: voice
    max_queue_time: 1s
  v_hydra_escped:
    file: cmgg2_hydra_escaped.ogg
    volume: 1
    track: voice
    max_queue_time: 1s
  v_additional_player_added:
    file: cmgg2_player_added.wav
    volume: 1
    track: voice
    max_queue_time: 0.25s
  v_game_not_over:
    file: cmgg2_game_not_over.wav
    volume: 1
    track: voice
    max_queue_time: 0.25s
  snd_cm_lead-in: #plays while ball in in shooter lane ready to plunge
    file: cm_lead-in.wav
#    volume: 1
    track: music
    streaming: false
#    loops: -1    #This is needed
    mode_end_action: stop_looping
  snd_cm_core0_arp_mute:
    file: cm_core0_arp_mute.wav
#    volume: 1
    track: music
#    loops: -1
    mode_end_action: stop_looping
  snd_cm_core0:
    file: cm_core0.wav
#    volume: 1
    track: music
#    loops: -1
    mode_end_action: stop_looping
  snd_cm_core1:
    file: cm_core1.wav
#    volume: 1
    track: music
#    loops: -1
    mode_end_action: stop_looping
  snd_cm_core_chords_no_arp:
    file: cm_core_chords_no_arp.wav
#    volume: 1
    track: music
#    loops: -1
    mode_end_action: stop_looping
  snd_cm_core_drum_solo:
    file: cm_core_drum_solo.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core_drum_solo_short:
    file: cm_core_drum_solo_short.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core0_fx_sweep:
    file: cm_core0_fx_sweep.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core_buildup:
    file: cm_core_buildup.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core_bass_interlude:
    file: cm_core_bass_interlude.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core0_fx_drum_fill_9sec:
    file: cm_core0_fx_drum_fill_9sec.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core0_fx_long:
    file: cm_core0_fx_long.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core1_fx_long:
    file: cm_core1_fx_long.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core0_ducking_drums:
    file: cm_core0_ducking_drums.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core1_ducking_drums:
    file: cm_core1_ducking_drums.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core0_all_synths_9sec:
    file: cm_core0_all_synths_9sec.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_drum_trans_short:
    file: cm_drum_trans_short.wav
    track: music
  snd_cm_drum_trans_very_short:
    file: cm_drum_trans_very_short.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core0_fx_echo:
    file: cm_core0_fx_echo.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core1_fx_echo:
    file: cm_core1_fx_echo.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_core_chords_runout:
    file: cm_core_chords_runout.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_mb_main1:
    file: cm_mb_main1.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_mb_main2:
    file: cm_mb_main2.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_mb_main3:
    file: cm_mb_main3.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_mb_main4:
    file: cm_mb_main4.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_mb_main_build:
    file: cm_mb_main_build.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_mb_interlude1:
    file: cm_mb_interlude1.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_mb_interlude2:
    file: cm_mb_interlude2.wav
    track: music
    mode_end_action: stop_looping
  snd_cm_mystery:
    file: cm_mystery.wav
    track: sfx
    volume: 0.6
    ducking:
      target: loops
      delay: 0.1 sec
      attack: 0.15 sec
      attenuation: 0 #-120db
      release_point: 0.01 sec
      release: 0.003 sec

#    file: cm_.wav
#    track: music
#    mode_end_action: stop_looping

  snd_cm_tail:
    file: cm_tail.wav
#    volume: 1
    track: music
#    loops: 1
  snd_startbutton:                      #### Add to attract
    file: cm_start-button.wav
    volume: 0.3
    track: sfx
    #events_when_stopped: finished_playing_start_button_sound #Later use this or loopplayer to make start chord not overlap shooter start

  snd_deadmans_intro:
    file: deadmans_intro.ogg
    volume: 0.8
    track: music
  snd_deadmansparty_riff:
    file: deadmansparty_riff.ogg
    volume: 0.6
    track: music
  snd_deadmans_tail:
    file: deadmans_tail.ogg
    volume: 0.6
    track: music
  snd_greymattershort1:
    file: greymattershort1.ogg
#    volume: 1
    track: music
  snd_greymatterlong:
    file: greymatterlong.ogg
    volume: 0.4
    track: music
  snd_bonus_riff3:
    file: cm_bonus_short.wav
    volume: 0.65
    track: music
    ducking:
      target: loops
      delay: 0.1 sec
      attack: 0.15 sec
      attenuation: 0 #-120db
      release_point: 0.01 sec
      release: 0.003 sec
  snd_cm_hydra0:
    file: cm_hydra0.wav
    track: music  #Dont know why this is not track loops
  snd_cm_hydra1:
    file: cm_hydra1.wav
    track: music
  snd_cm_goddess2_riff:
    file: cm_goddess2.wav
    volume: 0.4
    track: music
  snd_underworld_bonus_game_music:
    file: underworld_bonus_game_music.ogg
    volume: 0.6
    track: music
  snd_highscore_music:
    file: highscore_music.ogg
    volume: 0.6
    track: music
  snd_instructions_music:
    file: instructions_music.ogg
    volume: 0.25
    track: music

sound_loop_sets:
  riff_shooter_start:
    sound: snd_cm_lead-in
  riff_core0_arp_mute:
    sound: snd_cm_core0_arp_mute
  riff_core0:
    sound: snd_cm_core0
  riff_core1:
    sound: snd_cm_core1
  riff_core_chords_no_arp:
    sound: snd_cm_core_chords_no_arp
  riff_core_drum_solo:
    sound: snd_cm_core_drum_solo
  riff_core_drum_solo_short:
    sound: snd_cm_core_drum_solo_short
  riff_core0_fx_sweep:
    sound: snd_cm_core0_fx_sweep
  riff_core_buildup:
    sound: snd_cm_core_buildup
  riff_core_bass_interlude:
    sound: snd_cm_core_bass_interlude
  riff_core0_fx_drum_fill9sec:
    sound: snd_cm_core0_fx_drum_fill_9sec
  riff_core0_fx_long:
    sound: snd_cm_core0_fx_long
  riff_core1_fx_long:
    sound: snd_cm_core1_fx_long
  riff_core0_ducking_drums:
    sound: snd_cm_core0_ducking_drums
  riff_core1_ducking_drums:
    sound: snd_cm_core1_ducking_drums
  riff_core0_all_synths_9sec:
    sound: snd_cm_core0_all_synths_9sec
  riff_drum_trans_short:
    sound: snd_cm_drum_trans_short
  riff_core0_fx_echo:
    sound: snd_cm_core0_fx_echo
  riff_core1_fx_echo:
    sound: snd_cm_core1_fx_echo
  riff_core_chords_runout:
    sound: snd_cm_core_chords_runout
  riff_drum_trans_very_short:
    sound: snd_cm_drum_trans_very_short
  riff_mb_main1:
    sound: snd_cm_mb_main1
  riff_mb_main2:
    sound: snd_cm_mb_main2
  riff_mb_main3:
    sound: snd_cm_mb_main3
  riff_mb_main4:
    sound: snd_cm_mb_main4
  riff_mb_main_build:
    sound: snd_cm_mb_main_build
  riff_mb_interlude1:
    sound: snd_cm_mb_interlude1
  riff_mb_interlude2:
    sound: snd_cm_mb_interlude2
  game_over_without_bonus:
    sound: snd_cm_tail
#  start_button_chord:
#    sound: snd_startbutton
#  bonus_intro:
#    sound: snd_deadmans_intro
  bonus_game_riff:
    sound: snd_underworld_bonus_game_music
  bonus_game_over:             #I cant see that this gets played anywhere, listen
    sound: snd_deadmans_tail
  bug_game_intro:
    sound: snd_greymattershort1
  bug_game_riff:
    sound: snd_greymatterlong
  hydra_battle_riff0:
    sound: snd_cm_hydra0
  hydra_battle_riff1:
    sound: snd_cm_hydra1
  goddess_mb_riff:
    sound: snd_cm_goddess2_riff
#  my_hades_bonus_music:
#    sound: snd_underworld_bonus_game_music
  my_highscore_music:
    sound: snd_highscore_music
  my_instructions_music:
    sound: snd_instructions_music #snd_instructions_music.ogg
