#config_version=5
#This is where kivy is configured and a couple booting slides are placed.
#To allow the display to be windowed graphics-> fullscreen has to be true and window->borderless has to be false.
#To see the switch status screen go to the top middle of the score display with mouse and grab the window bar pulling it downward

kivy_config:
  kivy:
    desktop: 1
    exit_on_escape: true
    pause_on_minimize: 0
  graphics:  # https://kivy.org/doc/stable/api-kivy.config.html#available-configuration-tokens
    borderless: true #was true under GG 1 Does not seem to do anything
    window_state: visible # and maximized allows it to exist in a window. Visible = whole screen visible, also valid: hidden, minimized
    fbo: hard  # hardware, software, force-hardware
    left: 0
    top: 0
    width: 3840 # 1920 works # 768 works
    height: 3184 #  2104 works #2104 works
    maxfps: 30
    multisamples: 2
    position: custom # auto, custom
    show_cursor: false
    resizable: true #when true after title bar grabbed, the window can be resized. false=nor resizing
    rotation: 0
#***********************************************************************************************************************************
# *************** Change next line to true to allow grabbing of menu bar and dragging display into a window              ***********
#***********************************************************************************************************************************
    fullscreen:  true #true leaves a title bar which can be grabbed allowing display to be windowed. False now title bar, no grabbing

window: #should be same as graphics above
  width: 3840 # 1920 #768 works
  height: 3184 #Was 3184 under GG1
  top: 0
  left: 0 #0 works
  borderless: false #This is what gives the bar at the top of the window allowing grabbbing

displays:
  window: #should be same as window above
    width: 3840 # 1920 # 768 works
    height: 3184 # 2104 #2104 works
  score_lcd: #size of primary monitor
    width: 3840 # 1920 # 768 works
    height: 2160 # 1080 # 1080 works
  playfield_lcd:
    width: 768
    height: 1024
# Aspect ratio of playfield picture is 508Wide by 1190 high


slides:
  layout_split:
    background_color: black
    widgets:
      - type: display #Kivi sees the small display as above the large display
        width: 3840 # 1920 # 768 works
        height: 2160 # 1080
        x: 0
        y: 1024
        anchor_x: left
        anchor_y: bottom #bottom works
        source_display: score_lcd
      - type: display
        width: 768
        height: 1024 #1016 works
        x: 0
        y: 0
        anchor_x: left
        anchor_y: bottom # bottom works
        source_display: playfield_lcd
  slide_1:
    background_color: blue
    widgets:
      - type: text
        text: Scoring Assets Loading
  slide_2:
    background_color: teal
    widgets:
      - type: text
        text: Playfield Assets Loading

slide_player:
  mc_ready: #event which triggers layout and two booting slides
    layout_split:
      target: window
    slide_1:
      target: score_lcd
    slide_2:
      target: playfield_lcd
