#config_version=5
#This is the mode for generating the linear light sweep when a ball drains It uses
#display_light_player and sends a kivi output to the playfield lights
#After the  sweep animation is complete it issues the eventdrain_sweep_complete
#which ends the mode, shuts down the display_light_player
#http://docs.missionpinball.org/en/latest/config_players/display_light_player.html?highlight=as%20display
#    width: 508
#    height: 1190
#Above 1000 or 84% is BB
#Below 980 upper apron
#Below 920 orbit
mode:
  priority: 2000
  stop_on_ball_end: false #Set these to false so the mode does not die before displaying the show at ball_drain
  game_mode: false
  start_events:
#    - balldevice_bd_scoop_ball_eject_attempt Starting from here crashes mode because AssertionError: Target <playfield.earth_pf> not ready
#    - ball_waiting_to_eject_from_scoop
    - balldevice_bd_trough_ball_enter #ball_drain #s_launch_active #ball_drain
  stop_events:
    - drain_sweep_complete


display_light_player:
  mode_drain_display_started:
    led_matrix:
      action: play
      lights: lanes, right_ballguide, left_ballguide #All lights
  mode_drain_display_ending:
    led_matrix:
      action: stop
      lights: lanes, right_ballguide, left_ballguide #All lights
#  mode_display_stopping:
#    action: stop

slide_player:
  mode_drain_display_started:
    blank_transparent:
      target: led_matrix
      background_color: 00000000 #Background with no opacity required
      widgets:
      - type: quad
        points: 0,0, 0,900, 508,900,  508,0
        color: red
        opacity: 0
        expire: 1s

widget_player:
  slide_blank_transparent_active:
    line_sweep:
      target: led_matrix
widgets:
  line_sweep:
  - type: quad
    color: red
    points: 0,300,  0,350, 508,350, 508,300
    anchor_x: left #center
    anchor_y: bottom
    z: 1
    expire: 0.5s
    events_when_removed: drain_sweep_complete
    animations:
      add_to_slide:
        - property: points
          value: 0,0, 0,50, 508,50, 508,0
          relative: false #true
          duration: 0.5s
          easing: linear #http://docs.missionpinball.org/en/latest/displays/widgets/easing.html
#        - property: opacity
#          value: 0.6
#          relative: false
#          duration: 0.5s
#          easing: linear #http://docs.missionpinball.org/en/latest/displays/widgets/easing.html
#          timing: with_previous
