#config_version=5
# This mode activates with p_locking_elgible. It then it calls for the lock to light via
# a hit to the ball_block target. After this the player locks a ball and mode quits. Second time
# through it locks a ball as before and then while still active calls for the MB start at the scoop.
# If the ball drains before the ball is locked, this mode starts when field starts because
# accrual base_p_locking_engaged.completed==True. State machine conditions against if this mode running.
# widget prompts to the player and light shows are handled in this mode.
# Qualifying a ball in olympus area raises BB for a hit to light O ramp lock. (This is handled in field)
# After the lock is full the state machine sends flap to face the O ramp until after MB is finished or
# until O lock is full in which case the diverter points to the middle
# and then a shot to the BB or ramp starts double MB.
#
#10-17-21 added accrual to track if light lock shot already hit so mode wont require this on restart if ball drains before ball locked
mode:
  priority: 1000 # range 100-1M
  start_events:
    - p_locking_elgible
    - mode_field_started{device.ball_devices.bd_poseidon_ramp.balls==2} #If lock already is full, calling for scoop shot
    - mode_field_started{device.accruals.base_p_locking_engaged.completed} #==True} #Starts the mode if the mode is qualified on prior ball
  stop_events:
    - multiball_poseidon_ramp_ended
    - kill_p_locking # used by mystery mode to shut down p_locking if sis in left position
    - multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1}
    - mode_goddess_mb_started #When field restarts this mode should respon if engaged completed

multiball_locks:
  poseidon_lock:
    source_playfield: earth_pf
    enable_events:
      - prmb_light_p_lock_hit
      - mode_p_ramp_mb_started{device.accruals.prmb_light_p_lock_already_hit.completed}
    disable_events:
      - multiball_poseidon_ramp_started
      - multiball_lock_poseidon_lock_locked_ball
    balls_to_lock: 2
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_poseidon_ramp
    balls_to_replace: 2 #2 #1=replace first ball locked from trough, use when triggering with lock full event.Default -1 = replace every ball locked with new ball
    debug: True

multiballs:
  poseidon_ramp:
    source_playfield: earth_pf
    ball_count: 2
    ball_count_type:  add # total # increase number of playfield balls to count
    ball_locks: bd_poseidon_ramp
    replace_balls_in_play: false #true # false leaves one in the lock see http://docs.missionpinball.org/en/latest/game_logic/multiballs/multiball_with_traditional_ball_lock.html
    enable_events:
      - mode_p_ramp_mb_started
    disable_events:
      - multiball_poseidon_ramp_ended
    start_events:
      - prmb_start_shot_hit
      - ormb_start_shot_hit
      - balldevice_bd_poseidon_ramp_ball_missing #Experimental fix for a ball that slipped through the lock 11/21/20
      - start_double_mb #Picks up a ramp opto hit broadcast by double ramp mb mode
    shoot_again: 10s #default ball save is 10 sec
    debug: true

shot_profiles:
  flashing_off_p:
    advance_on_hit: false
    loop: false
    states:
      - name: flashing
        show: flash
        speed: 3
      - name: off
        show: off

shots:
  prmb_light_p_lock:
    playfield: earth_pf
    profile: flashing_off_p
    enable_events:
      - mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls<2} #==0} #This enables the shot when mode starts provided lock not already full.
    reset_events: multiball_lock_poseidon_lock_locked_ball
    disable_events: prmb_light_p_lock_hit
    hit_events:
      - ball_block_hit
    debug: true
  prmb_start_shot:
    playfield: earth_pf
    profile: flashing_off_p
    enable_events:
      - multiball_lock_poseidon_lock_full
      - mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==2}
    disable_events: prmb_start_shot_hit
    hit_events: base_scoop_from_pf_hit
    debug: true
  prmb_jackpot:
    playfield: earth_pf
    profile: flashing_off_o
    enable_events: multiball_poseidon_ramp_started
    hit_events: base_poseidon_pop_hit
    debug: true
    persist_enable: false  #Otherwise can continue to jackpot later in game. Added day before Expo

variable_player:
  prmb_jackpot_hit:
    score: 2000

timers:
  prmb_allow_ball_block_to_settle: # used to allow ball block to register hit and activate timer in mode_scoop so timer can be paused. Replace this timer with show when appropriate
    #This timer was used when the scoop shot activated the multiball.  But this presented a problem for qualifying the other ramp's locks and was removed.
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: multiball_lock_poseidon_lock_full
        action: restart #reset to starting value and start

event_player:
  timer_prmb_allow_ball_block_to_settle_complete: pause_ball_block_timer #invite scoop shot
#  prmb_light_p_lock_hit: jump_ball_block_timer_to_1 #Raise the BB fast by jumping timer to 1
  poseidon_mech_hit: bonus_pop #used by counter in base for bonus calculation
#  multiball_lock_poseidon_lock_full: force_bb_down
#  multiball_poseidon_ramp_started: release_bb_override #commented out 11/15/20 because when next ball starts ball block raises #Reinstated 11/27 because it does not raise until scoop hit at next ball (keeping down for super spinner presumably)

show_player:
  #Things to do when starting
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls<2 and not device.accruals.prmb_light_p_lock_already_hit.completed}: #mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==0}:
    show_attention_ball_block:
      speed: 4
      sync_ms: 0
      show_tokens:
        color1: blue
        color2: stop
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==2}:
    show_attention_scoop:
      speed: 8
      show_tokens:
        color1: blue
        color2: black
  #Things to do when enable the lock shot hit
  prmb_light_p_lock_hit: #player has hit qualifying shot Here is where the locks are lit and arrow directs player to shoot ramp
    show_attention_ball_block:
      action: stop
    show_swirl_left_spk_blue:
      speed: 10
    show_p_ramp_mb_0_balls:
      speed: 20
    show_flash_ramp_arrow:
      speed: 4
      show_tokens:
        color: blue
  #Things to do when diverter moves
  ramp_flap_control_move_divert_right{device.multiball_locks.poseidon_lock.enabled}: #Diverter moved to other side
    show_flash_ramp_arrow:
      action: stop
  ramp_flap_control_move_divert_left{device.multiball_locks.poseidon_lock.enabled}: #Diverter moded back to correct side for locking ball
    show_flash_ramp_arrow:
      speed: 4
      show_tokens:
        color: blue
  #Things to do when lock is full
  multiball_lock_poseidon_lock_full:
    show_attention_scoop:
      speed: 8
      show_tokens:
        color1: blue
        color2: black
#  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2}:
    show_flash_ramp_arrow:
      action: stop
    show_p_ramp_mb_1_balls:
      action: stop
    show_p_ramp_mb_2_balls:
      speed: 20
  #Things to do when multiball started
  multiball_poseidon_ramp_started:
    show_attention_scoop:
      action: stop
    show_sparkle_gg_blue:
      speed: 40
    show_everything_blue:
      loops: -1 #speed: 1
    show_swirl_left_spk_blue:
      action: stop
    show_p_ramp_mb_2_balls:
      action: stop
    show_countdown99_blue:
      speed: 10
      loops: 0
  #Things to do when shutting down either from ball loss, first ball locked or MB ended
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1}:
    show_flash_ramp_arrow:
      action: stop
    show_p_ramp_mb_0_balls:
      action: stop
    show_p_ramp_mb_1_balls:
      speed: 20

widgets:
  shoot_scoop_target_blue:
    - type: text
      text: SHOOT  SCOOP  TARGET
      font_name: greekgods3
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: blue
      z: 5
      events_when_added: blue_message_added_to_slide_show_progress_to_ramp_mb
  shoot_scoop_blue:
    - type: text
      text: SHOOT  THE  SCOOP
      font_name: greekgods3
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: blue
      z: 5
      events_when_added: blue_message_added_to_slide_show_progress_to_ramp_mb
  qualified_blue:
    - type: text
      text: "Q\nU\nA\nL\nI\nF\nI\nE\nD"
      font_name: greekgods3
      color: green
      font_size: 58
      x: 144
      y: 160
      anchor_x: center
      anchor_y: bottom
      z: 5
      rotation: 0
  shoot_ramp_blue:
    - type: text
      text: SHOOT  THE  RAMP
      font_name: greekgods3
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: blue
      z: 5
      events_when_added: blue_message_added_to_slide_show_progress_to_ramp_mb
  move_sis_blue:
    - type: text
      text: ROLL  BOULDER  TO  OTHER  SIDE
      font_name: greekgods3
      font_size: 36
      x: 384
      y: 53
      anchor_x: center
      anchor_y: bottom
      color: blue
      z: 5
  announce_mb_pf:
    - type: image
      image: mb_3balls
      scale: 0.44
      anchor_x: center
      anchor_y: center
      x: 384
      y: 455
      z: 2
      animations:
        add_to_slide:
          - property: rotation
            value: 0
            relative: false
            duration: 0
          - property: rotation
            value: 360
            relative: false
            duration: 4s
            easing: linear #http://docs.missionpinball.org/en/latest/displays/widgets/easing.html
            repeat: true
  announce_mb_pf_mask:
    - type: image
      image: mb_mask
      scale: 0.5
      anchor_x: center
      anchor_y: bottom
      x: 394
      y: 155
      z: 1
  announce_blue_jackpot:
    - type: image
      image: jackpot_blue
      scale: 0.2
      anchor_x: center
      anchor_y: center
      x: 384
      y: 455
      z: 3
      animations:
        add_to_slide:
        - property: scale
          value: 1.2
          relative: false
          duration: 0.25
          easing: in_out_cubic
        - property: scale
          value: 0
          relative: false
          duration: 0.25
          easing: in_out_cubic

widget_player:
  #Things to do when starting
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls<2 and not device.accruals.prmb_light_p_lock_already_hit.completed}: #Mode started hasnt lit
    qualified_blue:
      slide: show_progress_to_ramp_mb #Adds widget on top of pillar of this slide which was posted in field
      action: add
    shoot_scoop_target_blue:
      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
      action: add
    #Remove anything that may be in the way
    shoot_scoop_target_yellow:
      action: remove
    shoot_ramp_yellow:
      action: remove
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls<2 and device.accruals.prmb_light_p_lock_already_hit.completed}: #Mode started has lit and lock not full
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: add
    #Remove anything that may be in the way
    shoot_scoop_target_yellow:
      action: remove
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==2}:
    shoot_scoop_blue:
      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
      action: add
    #Remove anything that may be in the way
    shoot_scoop_target_yellow:
      action: remove
    shoot_ramp_yellow:
      action: remove
  #Things to do when enable the lock shot hit
  prmb_light_p_lock_hit:
    qualified_blue:
      slide: show_progress_to_ramp_mb
      action: remove #show naked progress bar again for next qualify
    shoot_scoop_target_blue:
      slide: show_progress_to_ramp_mb
      action: remove #clean up
    #Remove anything else that may be in the way
    shoot_scoop_target_yellow:
      action: remove
    shoot_ramp_yellow:
      action: remove
  prmb_light_p_lock_hit{device.state_machines.ramp_flap_control.state=="divert_left"}: #diverter is on correct side to lock ball
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: add
  #Things to do when diverter moves
  ramp_flap_control_move_divert_right{device.multiball_locks.poseidon_lock.enabled}: #Diverter moved to other side
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: remove
    move_sis_blue:
      slide: show_progress_to_ramp_mb
      action: add
      widget_settings:
        expire: 8 sec
  ramp_flap_control_move_divert_left{device.multiball_locks.poseidon_lock.enabled}: #Diverter moded back to correct side for locking ball
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: add
    move_sis_blue:
      slide: show_progress_to_ramp_mb
      action: remove
    #Remove anything else that may be in the way
    shoot_scoop_target_yellow:
      action: remove
    shoot_ramp_yellow:
      action: remove
  #Things to do when lock is full
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2}:
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: remove
    shoot_scoop_blue:
      slide: show_progress_to_ramp_mb
      action: add
    #Remove anything else that may be in the way
    shoot_scoop_target_yellow:
      action: remove
    shoot_ramp_yellow:
      action: remove
  #Things to do when multiball started
  multiball_poseidon_ramp_started:
    shoot_scoop_blue:
      slide: show_progress_to_ramp_mb #clean up message when no longer needed
      action: remove
    announce_mb_pf:
      slide: show_progress_to_ramp_mb
      action: add
    announce_mb_pf_mask:
      slide: show_progress_to_ramp_mb
      action: add
  #Things to do when shutting down either from ball loss, first ball locked or MB ended
  mode_p_ramp_mb_ending: #clean up all the added widgets b/c ball drained or MB over
    move_sis_blue:
      action: remove
    shoot_scoop_target_blue:
      action: remove
    shoot_ramp_blue:
      action: remove
    announce_mb_pf:
      action: remove
    announce_mb_pf_mask:
      action: remove
  #Things to do when p_ramp_mb adds a widget
  #This is a hack to prevent competing messages to show at the same time.  A better long term
  #solution may be to put a mask behind each text widget that is added and removed with the
  #text allowing the messages to be layered.  This may not z correctly however and both modes
  #might have to be given the same Z or somehow the ramp mb's added into the same mode.
  yellow_message_added_to_slide_show_progress_to_ramp_mb: #pull off blue messages so they dont compete with updated blue one
    shoot_scoop_blue:
      slide: show_progress_to_ramp_mb
      action: remove
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: remove
  prmb_jackpot_hit:
    announce_blue_jackpot:
      target: playfield_lcd
      action: add
      widget_settings:
        expire: 0.5 sec



slide_player:
  right_ramp_hit{device.multiball_locks.poseidon_lock.enabled}:
    move_boulder_r2l:
      target: playfield_lcd
      expire: 3.3s
      widgets:
      - type: image
        image: sisr2l
        fps: 30
        scale: 0.5
        y: 65%
        z: 5000
      - type: text
        text: ROLL POWERBALL  TO  OTHER  SIDE
        font_name: greekgods3
        font_size: 36
        x: 384
        y: 53
        anchor_x: center
        anchor_y: bottom
        color: blue

accruals:
  # This designed to fire once to give instructions a single time during the game
  move_powerball_instructions_p:
    events:
      - right_ramp_hit{device.multiball_locks.poseidon_lock.enabled}
    persist_state: true
    reset_on_complete: false
    disable_on_complete: true
  #This one lets mode start with lock already lit
  prmb_light_p_lock_already_hit:
    events:
      - prmb_light_p_lock_hit
    restart_events:
      - multiball_lock_poseidon_lock_locked_ball
    persist_state: true
    reset_on_complete: false
    disable_on_complete: true

sound_player:
  multiball_poseidon_ramp_started: v_multiball
  multiball_lock_poseidon_lock_full: v_shoot_scoop_mb #defigned in sounds in config
  prmb_jackpot_hit: v_jackpot
  mode_p_ramp_mb_started{not device.accruals.prmb_light_p_lock_already_hit.completed}: v_shoot_scoop_target_to_enable_lock
  prmb_light_p_lock_hit{device.state_machines.ramp_flap_control.state=="divert_right" and not mode.o_ramp_mb.active}: v_move_powerball_to_other_side_to_lock_ball #Added conditional about other mode running to p and o rmb right before Expo to decrease false alarms
  prmb_light_p_lock_hit{device.state_machines.ramp_flap_control.state=="divert_left"}: v_shoot_ramp_to_lock_ball #diverter is on correct side to lock ball
  mode_p_ramp_mb_started{device.state_machines.ramp_flap_control.state=="divert_left" and device.accruals.prmb_light_p_lock_already_hit.completed}: v_shoot_ramp_to_lock_ball #diverter is on correct side to lock ball when mode started and lock lit
  logicblock_move_powerball_instructions_p_complete{not mode.o_ramp_mb.active}: v_move_powerball_to_other_side_to_lock_ball #Announces once if ramp hit with flap in wrong spot
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1 and device.multiball_locks.olympus_lock.locked_balls == 0}: v_ball_1_locked
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2 and device.multiball_locks.olympus_lock.locked_balls == 0}: v_ball_2_locked
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1 and device.multiball_locks.olympus_lock.locked_balls == 1}: v_ball_2_locked
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2 and device.multiball_locks.olympus_lock.locked_balls == 1}: v_ball_3_locked
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1 and device.multiball_locks.olympus_lock.locked_balls == 2}: v_ball_3_locked
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2 and device.multiball_locks.olympus_lock.locked_balls == 2}: v_ball_4_locked

#  multiball_lock_poseidon_lock_locked_ball{device.ball_locks.bd_poseidon_ramp.total_balls_locked == 2}: ball2locked
#multiball_lock_poseidon_lock_locked_ball'====== Args={'total_balls_locked': 1}
#multiball_lock_poseidon_lock_locked_ball
