#config_version=5
# This mode activates with p_locking_elgible. It then it calls for the lock to lite via
# a hit to the ball_block target. After this the player locks a ball and mode quits. Second time
# through it locks a ball as before and then while still active calls for the MB start at the scoop.
# If the ball drains before the ball is locked, this mode starts when field starts because
# accrual base_o_locking_engaged.completed==True
# widget prompts to the player and light shows are handled in this mode.
# Qualifying a ball in olympus area raises BB for a hit to light O ramp lock. (This is handled in field)
# After the lock is full the servo mode it turned off and the flap is sent to face the O ramp until after MB is finished or until O lock is full in which case the diverter points to the middle
# and then a shot to the BB or ramp starts double MB. When double MB started the diverter wags to divert to the left because that is more fun. (No wagging diverter during any MB)
# Do: Monitor lock light behavior when ball present after drain when next ball starts, might need conditional logic on mode start to show correct show.
mode:
  priority: 1000 # range 100-1M
  start_events:
    - p_locking_elgible
    - mode_field_started{device.ball_devices.bd_poseidon_ramp.balls==2} #If lock already is full, calling for scoop shot
    - mode_field_started{device.accruals.base_p_locking_engaged.completed} #==True} #Starts the mode if the mode is qualified on prior ball
  stop_events:
    - multiball_poseidon_ramp_ended
    - kill_p_locking # used by mystery mode to shut down p_locking if sis in left position
    - multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1}

multiball_locks:
  poseidon_lock:
    source_playfield: earth_pf
    enable_events:
      - prmb_light_p_lock_hit
    disable_events:
      - multiball_poseidon_ramp_started
      - multiball_lock_poseidon_lock_locked_ball
    balls_to_lock: 2
    locked_ball_counting_strategy: physical_only
    lock_devices: bd_poseidon_ramp
    balls_to_replace: 2 #2 #1=replace first ball locked from trough, use when triggering with lock full event.Default -1 = replace every ball locked with new ball
    debug: True

multiballs:
  poseidon_ramp:
    source_playfield: earth_pf
    ball_count: 2
    ball_count_type:  add # total # increase number of playfield balls to count
    ball_locks: bd_poseidon_ramp
    replace_balls_in_play: false #true # false leaves one in the lock see http://docs.missionpinball.org/en/latest/game_logic/multiballs/multiball_with_traditional_ball_lock.html
    enable_events:
      - mode_p_ramp_mb_started
    disable_events:
      - multiball_poseidon_ramp_ended
    start_events:
      - prmb_start_shot_hit
      - ormb_start_shot_hit
      - start_double_mb #Picks up a ramp opto hit broadcast by double ramp mb mode
    shoot_again: 10s #default ball save is 10 sec
    debug: true

shot_profiles:
  flashing_off_p:
    advance_on_hit: false
    loop: false
    states:
      - name: flashing
        show: flash
        speed: 3
      - name: off
        show: off

shots:
  prmb_light_p_lock:
    playfield: earth_pf
    profile: flashing_off_p
    enable_events:
      - mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls<2} #==0} #This enables the shot when mode starts provided lock not already full.
    reset_events: multiball_lock_poseidon_lock_locked_ball
    disable_events: prmb_light_p_lock_hit
    hit_events: ballblock_hit
    debug: true
  prmb_start_shot:
    playfield: earth_pf
    profile: flashing_off_p
    enable_events:
      - multiball_lock_poseidon_lock_full
      - mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==2}
    disable_events: prmb_start_shot_hit
    hit_events: base_scoop_from_pf_hit
    debug: true

timers:
  prmb_allow_ballblock_to_settle: # used to allow ball block to register hit and activate timer in mode_scoop so timer can be paused. Replace this timer with show when appropriate
    #This timer was used when the scoop shot activated the multiball.  But this presented a problem for qualifying the other ramp's locks and was removed.
    start_value: 1
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: multiball_lock_poseidon_lock_full
        action: restart #reset to starting value and start

event_player:
  timer_prmb_allow_ballblock_to_settle_complete: pause_ballblock_timer #invite scoop shot
  prmb_light_p_lock_hit: jump_ballblock_timer_to_1 #Raise the BB fast by jumping timer to 1
# multiball_poseidon_ramp_started: resume_ballblock_timer
  poseidon_mech_hit: bonus_pop #used by counter in base for bonus calculation
  multiball_lock_poseidon_lock_full{device.ball_devices.bd_olympus_ramp.balls<2}:
    - ramp_servo_divert_right #Olympus can accept balls
    - force_bb_down
  multiball_lock_poseidon_lock_full{device.ball_devices.bd_olympus_ramp.balls==2}:
    - ramp_servo_divert_middle #When both locks full
    - force_bb_down
  mode_poseidon_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==2}: ramp_servo_divert_right #Mode starting after a drain, and lock already full. moves diverter in case other player had diverter in wrong postion. bb_down handels dropping the ball block
  multiball_poseidon_ramp_started:
    - ramp_servo_divert_left #Send to left because more fun.
#    - release_bb_override #commented out 11/15/20 because when next ball starts ball block raises
#  multiball_lock_poseidon_lock_full: keep_bb_down
#  multiball_poseidon_ramp_started: release_bb_override

show_player:
  #Things to do when starting
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls<2}: #mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==0}:
    show_attention_ballblock:
      speed: 4
      sync_ms: 0
      show_tokens:
        color1: blue
        color2: stop
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==2}:
    show_attention_scoop:
      speed: 8
      show_tokens:
        color1: blue
        color2: black
  #Things to do when enable the lock shot hit
  prmb_light_p_lock_hit: #player has hit qualifying shot Here is where the locks are lit and arrow directs player to shoot ramp
    show_attention_ballblock:
      action: stop
    show_swirl_left_spk_blue:
      speed: 10
    show_p_ramp_mb_0_balls:
      speed: 20
    show_flash_ramp_arrow:
      speed: 4
      show_tokens:
        color: blue
  #Things to do when diverter moves
  ramp_flap_tracking_diverting_right{device.multiball_locks.poseidon_lock.enabled}: #Diverter moved to other side
    show_flash_ramp_arrow:
      action: stop
  ramp_flap_tracking_diverting_left{device.multiball_locks.poseidon_lock.enabled}: #Diverter moded back to correct side for locking ball
    show_flash_ramp_arrow:
      speed: 4
      show_tokens:
        color: blue
  #Things to do when lock is full
  multiball_lock_poseidon_lock_full:
    show_attention_scoop:
      speed: 8
      show_tokens:
        color1: blue
        color2: black
#  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2}:
    show_flash_ramp_arrow:
      action: stop
    show_p_ramp_mb_1_balls:
      action: stop
    show_p_ramp_mb_2_balls:
      speed: 20
  #Things to do when multiball started
  multiball_poseidon_ramp_started:
    show_attention_scoop:
      action: stop
    show_sparkle_gg_blue:
      speed: 40
    show_everything_blue:
      loops: -1 #speed: 1
    show_swirl_left_spk_blue:
      action: stop
    show_p_ramp_mb_2_balls:
      action: stop
    show_countdown99_blue:
      speed: 10
      loops: 0
  #Things to do when shutting down either from ball loss, first ball locked or MB ended
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1}:
    show_flash_ramp_arrow:
      action: stop
    show_p_ramp_mb_0_balls:
      action: stop
    show_p_ramp_mb_1_balls:
      speed: 20

widgets:
  shoot_scoop_target_blue:
    - type: text
      text: SHOOT  SCOOP  TARGET
      font_name: GreekGods2
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: blue
      events_when_added: blue_message_added_to_slide_show_progress_to_ramp_mb
  shoot_scoop_blue:
    - type: text
      text: SHOOT  THE  SCOOP
      font_name: GreekGods2
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: blue
      events_when_added: blue_message_added_to_slide_show_progress_to_ramp_mb
  qualified_blue:
    - type: text
      text: "Q\nU\nA\nL\nI\nF\nI\nE\nD"
      font_name: GreekGods2
      color: green
      font_size: 58
      x: 144
      y: 160
      anchor_x: center
      anchor_y: bottom
      rotation: 0
  shoot_ramp_blue:
    - type: text
      text: SHOOT  THE  RAMP
      font_name: GreekGods2
      font_size: 50
      x: 384
      y: 760
      anchor_x: center
      anchor_y: bottom
      color: blue
      events_when_added: blue_message_added_to_slide_show_progress_to_ramp_mb
  move_sis_blue:
    - type: text
      text: ROLL  BOULDER  TO  OTHER  SIDE
      font_name: GreekGods2
      font_size: 36
      x: 384
      y: 53
      anchor_x: center
      anchor_y: bottom
      color: blue
  announce_mb_bb:
    - type: image
      image: watercolormbsmall
      scale: 1.25
  announce_mb_pf:
    - type: image
      image: mb_3balls
      scale: 0.44
      anchor_x: center
      anchor_y: center
      x: 384
      y: 455
      z: 2
      animations:
        add_to_slide:
          - property: rotation
            value: 0
            relative: false
            duration: 0
          - property: rotation
            value: 360
            relative: false
            duration: 4s
            easing: linear #http://docs.missionpinball.org/en/latest/displays/widgets/easing.html
            repeat: true
  announce_mb_pf_mask:
    - type: image
      image: mb_mask
      scale: 0.5
      anchor_x: center
      anchor_y: bottom
      x: 394
      y: 155
      z: 1

widget_player:
  #Things to do when starting
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls<2}:
    qualified_blue:
      slide: show_progress_to_ramp_mb #Adds widget on top of pillar of this slide which was posted in field
      action: add
      widget_settings:
#        expire: 10 sec
        z: 5
    shoot_scoop_target_blue:
      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
      action: add
      widget_settings:
        z: 5
  mode_p_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls==2}:
    shoot_scoop_blue:
      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
      action: add
      widget_settings:
        z: 5
  #Things to do when enable the lock shot hit
  prmb_light_p_lock_hit:
    qualified_blue:
      slide: show_progress_to_ramp_mb
      action: remove #show naked progress bar again for next qualify
    shoot_scoop_target_blue:
      slide: show_progress_to_ramp_mb
      action: remove #clean up
  prmb_light_p_lock_hit{device.state_machines.ramp_flap.state=="divert_left"}: #diverter is on correct side to lock ball
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: add
      widget_settings:
        z: 5
  #Things to do when diverter moves
  ramp_flap_tracking_diverting_right{device.multiball_locks.poseidon_lock.enabled}: #Diverter moved to other side
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: remove
    move_sis_blue:
      slide: show_progress_to_ramp_mb
      action: add
      widget_settings:
        expire: 8 sec
        z: 5
  ramp_flap_tracking_diverting_left{device.multiball_locks.poseidon_lock.enabled}: #Diverter moded back to correct side for locking ball
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: add
      widget_settings:
        z: 5
    move_sis_blue:
      slide: show_progress_to_ramp_mb
      action: remove
  #Things to do when lock is full
  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2}:
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: remove
    shoot_scoop_blue:
      slide: show_progress_to_ramp_mb
      action: add
      widget_settings:
        z: 5
  #Things to do when multiball started
  multiball_poseidon_ramp_started:
    shoot_scoop_blue:
      slide: show_progress_to_ramp_mb #clean up message when no longer needed
      action: remove
    announce_mb_bb:
      target: score_lcd
      action: add
      widget_settings:
        expire: 8 sec
    announce_mb_pf:
      slide: show_progress_to_ramp_mb
      action: add
    announce_mb_pf_mask:
      slide: show_progress_to_ramp_mb
      action: add
  #Things to do when shutting down either from ball loss, first ball locked or MB ended
  mode_p_ramp_mb_ending: #clean up all the added widgets b/c ball drained or MB over
    move_sis_blue:
      action: remove
    shoot_scoop_target_blue:
      action: remove
    shoot_ramp_blue:
      action: remove
    announce_mb_bb:
      action: remove
    announce_mb_pf:
      action: remove
    announce_mb_pf_mask:
      action: remove
  #Things to do when p_ramp_mb adds a widget
  #This is a hack to prevent competing messages to show at the same time.  A better long term
  #solution may be to put a mask behind each text widget that is added and removed with the
  #text allowing the messages to be layered.  This may not z correctly however and both modes
  #might have to be given the same Z or somehow the ramp mb's added into the same mode.
  yellow_message_added_to_slide_show_progress_to_ramp_mb: #pull off blue messages so they dont compete with updated blue one
    shoot_scoop_blue:
      slide: show_progress_to_ramp_mb
      action: remove
    shoot_ramp_blue:
      slide: show_progress_to_ramp_mb
      action: remove

#  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1}:
#    shoot_ramp_blue:
#      slide: show_progress_to_ramp_mb
#      action: remove
#  p_locking_elgible_again: #second time through the locking loop
#    qualified_blue:
#      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
#      action: add
#      widget_settings:
#        expire: 10 sec
#        z: 5
#    shoot_scoop_target_blue:
#      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
#      action: add
#      widget_settings:
#        z: 5
#  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2}:
#    shoot_ramp_blue:
#      slide: show_progress_to_ramp_mb
#      action: remove
#    shoot_scoop_blue:
#      slide: show_progress_to_ramp_mb
#      action: add
#      widget_settings:
#        z: 5
#  mode_sis_right_starting:
#    move_sis_blue:
#      slide: show_progress_to_ramp_mb
#      action: add
#      widget_settings:
#        expire: 8 sec
#        z: 5
#  mode_o_ramp_mb_started{device.switches.s_sis_right.state==1}:
#    move_sis_blue:
#      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in field
#      action: add
#      widget_settings:
#        expire: 8 sec
#        z: 5

slide_player:
  right_ramp_hit{device.multiball_locks.poseidon_lock.enabled}:
    move_boulder_r2l:
      target: playfield_lcd
      expire: 3.3s
      widgets:
      - type: image
        image: sisr2l
        fps: 30
        scale: 0.5
        y: 65%
        z: 5000
      - type: text
        text: ROLL  BOULDER  TO  OTHER  SIDE
        font_name: GreekGods2
        font_size: 36
        x: 384
        y: 53
        anchor_x: center
        anchor_y: bottom
        color: blue

#images:
#  lockballsleft_gif:
#    load: mode_start
#    file: lockballsleft_gif
#  shoot_ramp4mb_gif:
#    load: mode_start
#    file: shoot_rampmb.gif

#sound_player:
#  mode_poseidon_ramp_mb_started{device.ball_devices.bd_poseidon_ramp.balls<2}: shootramplockballs
#  multiball_poseidon_ramp_started: multiball
#  multiball_lock_poseidon_lock_full: shoot_ramp_mb #defigned in sounds in config
#  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 1}: ball1locked
#  multiball_lock_poseidon_lock_locked_ball{device.multiball_locks.poseidon_lock.locked_balls == 2}: ball2locked
#  multiball_lock_poseidon_lock_locked_ball{device.ball_locks.bd_poseidon_ramp.total_balls_locked == 2}: ball2locked
#multiball_lock_poseidon_lock_locked_ball'====== Args={'total_balls_locked': 1}
#multiball_lock_poseidon_lock_locked_ball
