#config_version=5
# Mode activates when field_spins = 100 or mystery award show_award_super_spinner posts.
# When count from field completes, mode starts and mode lights arrows to designate left pop
# to activate super spinner.
# After every 25 hits to a spinner, shooting the left pop will collect an extra bonus.
# If the pop shot is hit, the mode continues, otherwise the mode ends without bonus.
# SS doubles the points and lightshow on the spinners. Autofire coil knocker
# has enables that look for this mode to start which makes the c_u_knocker
# gently pulses with each spinner activation. Sound will also give a thump
# lastly when super spinner is active hits to either olympus or poseidon area
# gives extra ticks on the excitement timers on base.
# It also doubles hits to hydra in field or in battle hydra mode
#Display of meander circles is in mode base.
mode:
  priority: 1400 # Run over base and MB modes so slides show
  start_events:
    - mystery_super_spinner #Award from mode_mystery subsiquent events in script hit the shot.
    - field_says_start_super_spinner_mode #Threshold set in field in counters section
    - ball_started{device.sequences.base_super_spinner_mode_engaged.enabled==True}
  stop_events:
    - logicblock_base_super_spinner_mode_engaged_complete #ball_drain{not device.shots.super_spinner_kickoff.enabled} #OK to end mode only if scoop has been hit  This ensures restart if drain before scoop hit
#    - timer_super_spinner_countdown_complete #Moved to base accrual logic
  restart_on_next_ball: false #restarting when qualified but scoop not yet hit is handled by conditional logic against the sequence in base

accruals:  # this is a way for modes to see if super spinner is indeed running and not just waiting for the start shot
  super_spinner_started:
    events: super_spinner_kickoff_hit
    reset_on_complete: False


#Maybe change these event names to ss_says_... and make new events in scoop mode startup section
#event_player:
#  mode_super_spinner_started:
#    - force_bb_down
#  super_spinner_kickoff_hit:
#    - release_bb_override

variable_player:
  base_orbit_spinner_hit{not device.shots.super_spinner_kickoff.enabled}: #Dont start until scoop hit
    score: 25 #give additional 25 points per spin
  base_olympus_spinner_hit{not device.shots.super_spinner_kickoff.enabled}:
    score: 50
  super_spinner_bonus_hit:
    score: 50000
  timer_super_spinner_countdown_tick:
    super_spinner_collect_time_remaining: #Cant show timer value directly on a slide, has to be through a player variable
      int: device.timers.super_spinner_countdown.ticks
      action: set
  counter_super_spinner_count_hit:
    rotations_display_variable:
      int: device.counters.super_spinner_count.value
      action: set

shot_profiles:
  flash_only:
    states:
      - name: flash  # step 2
        show: on
    loop: false

shots:
  super_spinner_kickoff: #This shot activates releases all the modes functions
    playfield: earth_pf
    profile: one_state
    switch: s_left_side_pop
    hit_events:
#      - base_scoop_from_pf_hit
      - mystery_forcing_ss_start
    enable_events:
      - mode_super_spinner_started
    disable_events:
      - super_spinner_kickoff_hit

  super_spinner_bonus:
    playfield: earth_pf
    profile: flash_only
    switch: s_left_side_pop
    enable_events: super_spinner_bonus_threshold
    disable_events:
      - timer_super_spinner_countdown_complete
      - super_spinner_bonus_hit
  super_spinner_poseidon_mech:
    playfield: earth_pf
    profile: one_state #defigned in base
    hit_events:
      - base_poseidon_pop_hit
      - base_poseidon_left_slingshot_hit
      - base_poseidon_right_slingshot_hit
      - base_poseidon_gate_hit
    enable_events:
      - super_spinner_kickoff_hit
  super_spinner_olympus_mech:
    playfield: earth_pf
    profile: one_state #defigned in base
    hit_events:
      #- base_olympus_spinner_hit
      - base_olympus_right_pop_hit
      - base_olympus_lower_pop_hit
      - base_olympus_left_pop_hit
      - base_hole_proximal_hit
    enable_events:
      - super_spinner_kickoff_hit

counters:
  super_spinner_count:
    count_events:
      - base_orbit_spinner_hit
      - base_olympus_spinner_hit
    persist_state: false #does not reset when ball drains
#    disable_events: mode_hydra_started #Turn off the bonus shots if in hydra mb
    enable_events:
      - super_spinner_kickoff_hit
#      - mode_hydra_stopping #Turn it back on when mode hydra finished
    count_complete_value: 25
    restart_events: super_spinner_bonus_hit
#    reset_on_complete: true
    events_when_complete: super_spinner_bonus_threshold
    debug: true

timers:
  super_spinner_countdown:
    start_value: 12
    end_value: -1
    direction: down
    tick_interval: 1s
    control_events:
      - action: restart
        event:  super_spinner_bonus_threshold
      - action: stop
        event: super_spinner_bonus_hit
show_player:
  mode_super_spinner_started:
    show_invite_pop_shot:
      speed: 2
  super_spinner_kickoff_hit:
    show_invite_pop_shot:
      action: stop
  base_orbit_spinner_hit{not device.shots.super_spinner_kickoff.enabled}: #Dont show unless pop shot has already been hit
    show_super_orbit_spinner:
      speed: 10
      loops: 0
  base_olympus_spinner_hit{not device.shots.super_spinner_kickoff.enabled}:
    show_super_olympus_spinner:
      speed: 10
      loops: 0
  super_spinner_bonus_threshold:
    show_invite_pop_shot:
      speed: 2
  timer_super_spinner_countdown_complete:
    show_invite_pop_shot:
      action: stop
  super_spinner_bonus_hit:
    show_invite_pop_shot:
      action: stop
#  mode_super_spinner_started:
#    show_super_spinner_start:
#      speed: 1
#      loops: 0
#      events_when_completed: super_spinner_start_show_completed #releases ball hold in mode scoop.yaml

widgets:
  invite_super_spinner:
    - type: image
      image: wedge_super_spinner_inv
      scale: 0.30
      rotation: 80
      x: 410
      y: 660
      anchor_x: center
      anchor_y: center
  invite_super_spinner_pop_shot:
    - type: image
      image: wedge_collect_ss_bonus_inv
      scale: 0.32
      rotation: 45
      x: 200
      y: 300
      anchor_x: center
      anchor_y: center
      z: 4
  super_spinner_bonus_count:
    - type: text
      text: (player|rotations_display_variable)
      y: 88%
      font_size: 90
      color: red
      font_name: greekgods3
      expire: 2s
      z: 3 #Temple layer is 2
      animations:
        add_to_slide:
          - property: rotation
            value: 360
            relative: false
            duration: 2s
            easing: out_bounce #in_out_elastic #http://docs.missionpinball.org/en/latest/displays/widgets/easing.html
  super_spinner_time_remaining:
    - type: text
      text: (player|super_spinner_collect_time_remaining)
      font_size: 60
      color: black
      anchor_x: center
      anchor_y: center
      y: 10%
      x: 49%
      z: 5
  super_spinner_bonus_collected:
    - type: text
      text: Bonus Collected
      y: 77%
      font_size: 80
      color: green
      font_name: greekgods3
      expire: 2s
      z: 4 #Temple layer is 2
      animations:
        add_to_slide:
          - property: rotation
            value: 360
            relative: false
            duration: 1s
            easing: out_bounce #in_out_elastic #http://docs.missionpinball.org/en/latest/displays/widgets/easing.html
widget_player:
  mode_super_spinner_started:
    invite_super_spinner:
      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in temple display
      action: add
      widget_settings:
        expire: 10 sec
        z: 5
  super_spinner_kickoff_hit:
    invite_super_spinner:
      slide: show_progress_to_ramp_mb #Adds widget on top of this slide which was posted in temple display
      action: remove
  counter_super_spinner_count_hit:
    super_spinner_bonus_count:
      slide: show_progress_to_ramp_mb
  super_spinner_bonus_threshold:
    invite_super_spinner_pop_shot:
      slide: show_progress_to_ramp_mb
    super_spinner_time_remaining:
      slide: show_progress_to_ramp_mb
  timer_super_spinner_countdown_complete:
    invite_super_spinner_pop_shot:
      slide: show_progress_to_ramp_mb
      action: remove
  super_spinner_bonus_hit:
    invite_super_spinner_pop_shot:
      slide: show_progress_to_ramp_mb
      action: remove
    super_spinner_time_remaining:
      slide: show_progress_to_ramp_mb
      action: remove
    super_spinner_bonus_collected:
      slide: show_progress_to_ramp_mb
      action: add

slide_player:
  super_spinner_kickoff_hit:
    tada_super_spinner:
      target: playfield_lcd
      background_color: black
      expire: 4s
      widgets:
      - type: image
        image: meander_circle1invert
        scale: 0.75
        z: 1
        animations:
          add_to_slide:
          - property: rotation
            value: 0
            relative: false
            duration: 0
          - property: rotation
            value: 360
            relative: false
            duration: 4s
            easing: linear #http://docs.missionpinball.org/en/latest/displays/widgets/easing.html
            repeat: true
      - type: text
        text: "SUPER\nSPINNER\nENGAGED"
        font_name: greekgods3
        color: white
        y: 50%
        anchor_x: center
        anchor_y: center
        font_size: 60

sound_player:
  super_spinner_kickoff: v_super_spinner_engaged
  super_spinner_bonus_threshold: v_hit_the_lower_pop_for_bonus
