#config_version=5
#issues most sound effects and all music loops.

mode:
  start_events: mode_attract_started #game_started #, non-game mode?
  priority: 175 # range 100-1M
  game_mode: false


sound_player:
  #these instructions each play once early in game
  logicblock_sound_drop_target_instructions_complete: v_complete_drop_targets_to_qualify_mystery_mode
  logicblock_sound_revealed_band_instructions_complete: v_hit_blinking_band_enable_mystery_award
  logicblock_sound_ready_for_mystery_instructions_complete: v_shoot_orbit_hole_for_mystery_award
  logicblock_sound_lane_light_instructions_complete: v_completed_lane_lights_award_bs
# logicblock_sound_tracking_base_pops_complete: v_hit_all_pops_to_summon_goddess
  logicblock_sound_ready_locks_by_scoring_instructions_complete: v_ready_locks_by_scoring
  logicblock_sound_outlane_ballsave_instructions_complete: v_shoot_ramp_twice_outlane_protection
  logicblock_sound_use_knee_switch_complete: v_use_knee_switch
  logicblock_sound_poseidon_bonus_scoring_complete: v_poseidon_bonus_scoring #this is a sequence not a accrual
  logicblock_sound_olympus_bonus_scoring_complete: v_olympus_bonus_scoring

#  ball_starting{player==1 and ball==1}: v_welcome # mode_base_started'====== Args={'queue': <QueuedEvent>, 'player': 1, 'ball': 1,

#  mode_av_server_2k_started: snd_startbutton
  extra_ball_awarded: v_extra_ball_awarded
  player_added: snd_startbutton
  player_added{game.num_players>1}: v_additional_player_added
  base_right_slingshot_hit: snd_right_main_ss
  base_left_slingshot_hit: snd_left_main_ss
  base_left_inlane_hit: snd_shield
  base_left_outlane_hit: snd_shield
  base_right_inlane_hit: snd_shield
  base_right_outlane_hit: snd_shield
  base_hole_distal_hit: snd_shield
  base_hole_proximal_hit: snd_shield
  base_orbit_spinner_hit: snd_spinner
  base_olympus_spinner_hit: snd_spinner
  base_poseidon_gate: snd_poseidon_mech
  base_olympus_lower_pop_hit: snd_olympus_mech
  base_olympus_left_pop_hit: snd_olympus_mech
  base_olympus_right_pop_hit: snd_olympus_mech
  base_poseidon_pop_hit: snd_poseidon_mech
  base_poseidon_right_slingshot_hit: snd_poseidon_mech
  base_poseidon_left_slingshot_hit: snd_poseidon_mech
  base_left_side_pop_hit: snd_scott_pop
  base_hydra_hit: snd_hydra
  base_ramp_hit: snd_spinner
  base_revealed_slingshot_hit: snd_scott_pop
  left_ramp_hit{not (mode.olympus_ramp_mb.active or mode.poseidon_ramp_mb.active)}: snd_ramp_1  #used for lock flash show and banked ball save
  right_ramphit{not (mode.olympus_ramp_mb.active or mode.poseidon_ramp_mb.active)}: snd_ramp_2 #used for lock flash show and banked ball save
  bonus_orbit_counter_clockwise_hit: snd_orbit #used in bonus counting, for other orbit purposes, see field
  bonus_orbit_clockwise_hit: snd_orbit #used in bonus counting, for other orbit purposes, see field
  ball_block_hit: snd_drop_3 #records hit to the ball block drop target. control of the drop is via bd events in mode scoop.
#  base_scoop_from_pf: #This logs hits only when the scoop receives the ball from the front. Alternatively might be able to code this using delay_switch
  ball_waiting_to_eject_from_scoop: explosionlong
  base_sis_left_arrived_hit: snd_sis #divert_left
  base_sis_right_arrived_hit: snd_sis #divert_right
  mystery_hole_received_ball_hit: snd_cm_mystery
  base_hestia_summoned: v_goddess_awarded
  base_artemus_summoned: v_goddess_awarded
  base_athena_summoned: v_goddess_awarded
  base_aphrodite_summoned: v_goddess_awarded
  ball_save_bs_default_saving_ball: v_ball_saved
  ball_save_bs_scoop_eject_saving_ball: v_ball_saved

  base_double_left_ramp_hit{not mode.banked_l_bs.active}: v_outlane_bs_awarded
  base_double_right_ramp_hit{not mode.banked_r_bs.active}: v_outlane_bs_awarded
  bottom_lane_group_hit_complete: v_outlane_bs_awarded

  river_a_hit: snd_river
  river_b_hit: snd_river
  river_c_hit: snd_river
  river_d_hit: snd_river
  #Bug mode sounds
  river_a_bug_hit: snd_splat-and-crunch
  river_b_bug_hit: snd_splat-and-crunch
  river_c_bug_hit: snd_splat-and-crunch
  river_d_bug_hit: snd_splat-and-crunch
  left_corner_target_hit: snd_splat-and-crunch
  right_corner_target_hit: snd_splat-and-crunch
  middle_target_hit: snd_splat-and-crunch
  mode_hades_bug_game_started: v_help_hades
  all_bugs_smashed: v_underworld_cleansed
  lost_the_bug_ball: cmgg2_you_returned_underworld.ogg
  logicblock_ball_traversed_left_rivers_complete: snd_bat1
  logicblock_ball_traversed_right_rivers_complete: snd_bat3
  key_8_pressed: snd_bonus_riff3
  game_start:
    snd_startbutton:
      action: play
    snd_cm_tail:
      action: stop
      fade_out: 400 ms
  mode_bonus_started: snd_bonus_riff3 #End of ball bonus
  mode_bonus_stopping:
    snd_bonus_riff3:
      action: stop
      fade_out: 400 ms
  mode_game_stopping: snd_cm_tail
  high_score_enter_initials: snd_highscore_music
  mode_high_score_stopping:
    snd_highscore_music: #Shouldnt this be my_highscore_music?
      action: stop
      fade_out: 400 ms
  timer_instructions_clock_started: snd_instructions_music #starts the instructions loop in attract
  logicblock_instruction_slide_controller_complete:
    snd_instructions_music:
      action: stop
      fade_out: 400 ms
  mode_attract_will_stop:
    snd_instructions_music:
      action: stop
      fade_out: 100 ms
#Sound loops will loop play sound loop sets defined in sound.  Each is played as a pair of riffs that recombine for variety.  The starting of
#the pair is usually commanded by the state machine riffer which is living in base.  It needs to live somewhere that it can die and reset with each ball
# it should probably get its own mode with the accruals that are used by this mode.


# To turn off music can use track player like scott does with mystery mode.
sound_loop_player:
#  relies on sound_loop_sets currently defigned at the bottom of sound config.
# the events which trigger the sound loops are issued by the state machine in base

  ball_started:
    loops:
      sound_loop_set: riff_shooter_start
      action: play
      timing: now #now #was loop end but that made no sense because bonus music does not come through loop player
  #Base contains a state machine called riffer which directs the sound loop player into playing one of these themes. Each theme loops with subthemes
  #If not advancing properly make sure sound loop set name is correct. It does not crash if name invalid it just repeats last valid loop.
  loop_main_theme_music_level_1:
    loops:
      sound_loop_set: riff_core0_arp_mute
      action: play
      timing: now #loop_end
      events_when_played: make_loop_with_core0_of_lvl_1
  make_loop_with_core0_of_lvl_1:
    loops:
      sound_loop_set: riff_core0
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core1_of_lvl_1
  make_loop_with_core1_of_lvl_1:
    loops:
      sound_loop_set: riff_core1
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core_chords_no_arp_of_lvl_1
  make_loop_with_core_chords_no_arp_of_lvl_1:
    loops:
      sound_loop_set: riff_core_chords_no_arp
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_of_lvl_1

  loop_main_theme_music_level_2:
    loops:
      sound_loop_set: riff_core_drum_solo
      action: play
      timing: now #loop_end
      events_when_played: make_loop_with_core0_fx_sweep_of_lvl_2
  make_loop_with_core0_fx_sweep_of_lvl_2:
    loops:
      sound_loop_set: riff_core0_fx_sweep
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core1_of_lvl_2
  make_loop_with_core1_of_lvl_2:
    loops:
      sound_loop_set: riff_core1
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core_chords_no_arp_of_lvl_2
  make_loop_with_core_chords_no_arp_of_lvl_2:
    loops:
      sound_loop_set: riff_core_chords_no_arp
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_fx_sweep_of_lvl_2

  loop_main_theme_music_level_3:
    loops:
      sound_loop_set: riff_core_buildup
      action: play
      timing: now #loop_end
      events_when_played: make_loop_with_core_bass_interlude_of_lvl_3
  make_loop_with_core_bass_interlude_of_lvl_3:
    loops:
      sound_loop_set: riff_core_bass_interlude
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_fx_drum_fill9sec_of_lvl_3
  make_loop_with_core0_fx_drum_fill9sec_of_lvl_3:
    loops:
      sound_loop_set: riff_core0_fx_drum_fill9sec
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_fx_long_of_lvl_3
  make_loop_with_core0_fx_long_of_lvl_3:
    loops:
      sound_loop_set: riff_core0_fx_long
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core1_fx_long_of_lvl_3
  make_loop_with_core1_fx_long_of_lvl_3:
    loops:
      sound_loop_set: riff_core1_fx_long
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_ducking_drums_lvl_3
  make_loop_with_core0_ducking_drums_lvl_3:
    loops:
      sound_loop_set: riff_core0_ducking_drums
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core1_ducking_drums_lvl_3
  make_loop_with_core1_ducking_drums_lvl_3:
    loops:
      sound_loop_set: riff_core1_ducking_drums
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_fx_drum_fill9sec_of_lvl_3

  loop_main_theme_music_level_4:
    loops:
      sound_loop_set: riff_core_buildup
      action: play
      timing: now #loop_end
      events_when_played: make_loop_with_core_drum_solo_short_of_lvl_4
  make_loop_with_core_drum_solo_short_of_lvl_4:
    loops:
      sound_loop_set: riff_core_drum_solo_short
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_all_synths_9sec_of_lvl_4
  make_loop_with_core0_all_synths_9sec_of_lvl_4:
    loops:
      sound_loop_set: riff_core0_all_synths_9sec
      action: play
      timing: loop_end
      events_when_played: make_loop_with_drum_trans_short_of_lvl_4
  make_loop_with_drum_trans_short_of_lvl_4:
    loops:
      sound_loop_set: riff_drum_trans_short
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_fx_echo_of_lvl_4
  make_loop_with_core0_fx_echo_of_lvl_4:
    loops:
      sound_loop_set: riff_core0_fx_echo
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core1_fx_echo_of_lvl_4
  make_loop_with_core1_fx_echo_of_lvl_4:
    loops:
      sound_loop_set: riff_core1_fx_echo
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core0_ducking_drums_lvl_4
  make_loop_with_core0_ducking_drums_lvl_4:
    loops:
      sound_loop_set: riff_core0_ducking_drums
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core1_ducking_drums_lvl_4
  make_loop_with_core1_ducking_drums_lvl_4:
    loops:
      sound_loop_set: riff_core1_ducking_drums
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core_chords_runout_of_lvl_4
  make_loop_with_core_chords_runout_of_lvl_4:
    loops:
      sound_loop_set: riff_core_chords_runout
      action: play
      timing: loop_end
      events_when_played: make_loop_with_core_drum_solo_short_of_lvl_4

  loop_mb_music:
    loops:
      sound_loop_set: riff_drum_trans_very_short #Sounds better main 2 then main 1
      action: play
      timing: now
      events_when_played: make_loop_with_mb_main2
  make_loop_with_mb_main2:
    loops:
      sound_loop_set: riff_mb_main2 #Sounds better main 2 then main 1
      action: play
      timing: loop_end
      events_when_played: make_loop_with_mb_main1
  make_loop_with_mb_main1:
    loops:
      sound_loop_set: riff_mb_main1
      action: play
      timing: loop_end
      events_when_played: make_loop_with_mb_main_build1
  make_loop_with_mb_main_build1:
    loops:
      sound_loop_set: riff_mb_main_build
      action: play
      timing: loop_end
      events_when_played: make_loop_with_mb_interlude1
  make_loop_with_mb_interlude1:
    loops:
      sound_loop_set: riff_mb_interlude1
      action: play
      timing: loop_end
      events_when_played: make_loop_with_mb_main3
  make_loop_with_mb_main3:
    loops:
      sound_loop_set: riff_mb_main3
      action: play
      timing: loop_end
      events_when_played: make_loop_with_mb_main4
  make_loop_with_mb_main4:
    loops:
      sound_loop_set: riff_mb_main4
      action: play
      timing: loop_end
      events_when_played: make_loop_with_mb_main_build2
  make_loop_with_mb_main_build2:
    loops:
      sound_loop_set: riff_mb_main_build #reusing same build
      action: play
      timing: loop_end
      events_when_played: make_loop_with_mb_interlude2
  make_loop_with_mb_interlude2:
    loops:
      sound_loop_set: riff_mb_interlude2
      action: play
      timing: loop_end
      events_when_played: loop_mb_music

  mode_hades_bug_game_started:
    loops:
      sound_loop_set: bug_game_riff
      action: play
      timing: now

  mode_hades_bug_game_stopping: #This drops into the first looping sequence which is corrected with the followin command from state machine in base
    loops:                      #ideally state machine would have another state for detour music this this but this hack will hopefully serve.
      sound_loop_set: riff_core0
      action: play
      timing: now
      events_when_played: make_loop_with_core1_of_lvl_1

  ball_will_end:
    loops:
      action: stop

  mode_hades_bonus_game_started:
    loops:
      sound_loop_set: bonus_game_riff #my music
      action: play
      timing: now
#  mode_hades_bonus_game_started:
#    loops:
#      sound_loop_set: bonus_intro
#      action: play
#      timing: now
#      events_when_played: loop_deadmans_party_riff
#  loop_deadmans_party_riff:
#    loops:
#      sound_loop_set: bonus_riff
#      action: play
#      timing: now
  mode_hades_bonus_game_stopping:
    loops:
      action: stop
  game_ending:
    loops:
      action: stop
  mode_hydra_started:
    loops:
      sound_loop_set: hydra_battle_riff
      action: play
      timing: now
  mode_hydra_stopping: #This drops into the first looping sequence which is corrected with the followin command from state machine in base
    loops:                      #ideally state machine would have another state for detour music this this but this hack will hopefully serve.
      sound_loop_set: riff_core0
      action: play
      timing: now
      events_when_played: make_loop_with_core1_of_lvl_1

  mode_goddess_mb_started:
    loops:
      sound_loop_set: goddess_mb_riff
      action: play
      timing: now
  mode_goddess_mb_stopping: #This drops into the first looping sequence which is corrected with the followin command from state machine in base
    loops:                      #ideally state machine would have another state for detour music this this but this hack will hopefully serve.
      sound_loop_set: riff_core0
      action: play
      timing: now
      events_when_played: make_loop_with_core1_of_lvl_1
