#config_version=5
hardware:
  platform: p3_roc
  driverboards: pdb
p_roc:
   debug: True
   burst_us_per_half_pulse: 12
   burst_number_of_pulses_to_drive_output: 9
   burst_number_of_idle_pulses_before_next: 9
   burst_number_of_burst_pulses_before_check: 10
   burst_ms_between_scans: 1
#p_roc:
#  debug: true
#p3_roc:
#  debug: true
#  use_watchdog: true
#  watchdog_time: 1s
machine:
  balls_installed: 4
  min_balls: 1

config:
- hardware

modes:
  - base
  - ball_just_launched
#  - 2x_poseidon
#  - 2x_zeus
  - sismedial
  - sislateral
#  - hungry_holema10

light_player:
  poseidon_hunger_hit:
    poseidon_flashers
  zeus_hunger_hit:
    zeus_flashers
  z1_hit:
    zeus_flashers
  z2_hit:
    zeus_flashers
  z3_hit:
    zeus_flashers
  mode_game_started:
    l_backlight_w:
      color: white

ball_saves:
    default:
        active_time: 6s
        hurry_up_time: 2s
        grace_period: 2s
        enable_events: mode_base_started
        timer_start_events: balldevice_bd_trough_ball_eject_success
        auto_launch: yes
        balls_to_save: 1
        debug: yes

#displays:
#  window:
#    width: 800
#    height: 600
#    default: true
#    title: Greek Gods
#  playfield:
#    width: 640
#    heigth: 480
#    default: true
#displays:
#  top: 100
#  left: 400
window:
  width: 1536
  height: 1016
  top: 0
  left: 1152
  borderless: true
  fullscreen: false
displays:
  window:
    width: 1536
    height: 1016
  score_lcd:
    width: 768
    height: 1016
  playfield_lcd:
    width: 768
    height: 1016


#  default: true
#    title: Greek Gods #does not show when borderless
#    source_display: default
#    exit_on_escape: true #does not seem to do anything
#  effects: dmd
#    borderless: true
slides:
  layout_split:
    background_color: red
    widgets:
      - type: display
        width: 768
        height: 1016
        x: 0
        y: 0
        anchor_x: left
        anchor_y: bottom
        source_display: score_lcd
      - type: display
        width: 768
        height: 1016
        x: 768
        y: 0
        anchor_x: left
        anchor_y: bottom
        source_display: playfield_lcd
  slide_1:
    background_color: blue
    widgets:
      - type: text
        text: Scoring  Rrroading
  slide_2:
    background_color: teal
    widgets:
      - type: text
        text: Playfield  Rrroading

slide_player:
  mc_ready:
    layout_split:
      target: window
    slide_1:
      target: score_lcd
    slide_2:
      target: playfield_lcd

#slides:
#  welcome_slide:
#    widgets:
#      - type: text
#        text: Rrroading...
#        font_size: 50
#        color: red
#      - type: rectangle
#        width: 300
#        height: 60
#
#slide_player:
#  init_done: welcome_slide
