#config_version=5
# This mode activates when there have been a sufficient number of drop target shots hit during field. Strategicly it can be used to qualify olympus and poseidon ramp locking mode.
# Do: In field, add a visual que on the screen for how many drops hit
mode:
  priority: 600 # range 100-1M
  start_events:
    - drop_target_threshold_for_celestial_mb_met
  stop_events:
     - multiball_celestial_mb_ended

variable_player:
  base_right_slingshot_hit:
    score: 100 #* current_player.multiplier #page 506 dev
  base_left_slingshot_hit:
    score: 100
  drop_target_star_proximal_down:
    score: 150
  drop_target_star_middle_down:
    score: 150
  drop_target_star_distal_down:
    score: 150
  star_double_down_a:
    score: 100
  star_double_down_b:
    score: 100
  star_tripple_down:
    score: 200
  drop_target_bank_cluster_down: #Completed all 3 down
    score: 300
  base_revieled_slingshot_hit:
    score: 1000
  ballblock_hit:
    score: 500
  base_scoop_from_pf_hit:
    score: 500
  base_left_side_pop_hit:
    score: 200
  base_left_inlane_hit:
    score: 100
  base_left_outlane_hit:
    score: 200
  base_right_inlane_hit:
    score: 100
  base_right_outlane_hit:
    score: 200


multiballs:
  celestial_mb:
    source_playfield: earth_pf
    ball_count: 2
    ball_count_type: add  # increase number of playfield balls by couny
    shoot_again: 10s #ball save for MB 10 sec is default
    start_events: mode_celestial_mb_started
    enable_events: mode_celestial_mb_starting
    debug: true


#show_player:
#make a ball save counter that rainbows
# make a whold rainbow show   mode_poseidon_ramp_mb_started:
#    swirl_L_spk_blue:
#      speed: 10


show_player:
  multiball_celestial_mb_started:
#    show_revealed_slingshot_rainbow:
#      speed: 2
    show_rainbow_all_but_bs:
      speed: 2
    countdown99_white:
      speed: 10
      loops: 0

slide_player:
  mode_celestial_mb_started:
# Move this slide to av server and make is show when celest mb is due to start on next hit
#    celestial_mb_first_playfield_slide:
#      target: playfield_lcd
#      background_color: black
#      expire: 5s
#      widgets:
#      - type: image
#        image: dropsrainbow2 #rainbow_completion_gif
#        scale: 0.7
#        y: 60%
#        z: 100
#      - type: text
#        text: Celestial Multiball!
#        color: FFFFFF
#        y: 2%
#        anchor_x: center
#        anchor_y: bottom
#        font_size: 80
#        z: 200  mode_celestial_mb_started:
    pf_celestial_mb_started_slide:
      target: playfield_lcd
      background_color: black
      widgets:
      - type: text
        text: Double Scoring in
        color: white
        y: 55%
        anchor_x: center
        anchor_y: center
        font_size: 40
      - type: text
        text: Lower Playfield
        color: white
        y: 45%
        anchor_x: center
        anchor_y: center
        font_size: 40
    bb_celestial_mb_started_slide:
      target: score_lcd
      expire: 3s
      background_color: black
      widgets:
      - type: image
        image: watercolormb
        scale: 1.8
        z: 100
      - type: text
        text: Celestial
        color: white
        y: 2%
        anchor_x: center
        anchor_y: bottom
        font_size: 300
        z: 200



widget_player: #http://docs.missionpinball.org/en/latest/config/widget_player.html
  base_left_side_pop_hit:
    big_rainbow_left_to_right:
      target: playfield_lcd
  base_revieled_slingshot_hit:
    big_rainbow_right_to_left:
      target: playfield_lcd
  base_left_slingshot_hit:
    rainbow_diagnal_bottom_left_to_top_right:
      target: playfield_lcd
  base_right_slingshot_hit:
    rainbow_diagnal_bottom_right_to_top_left:
      target: playfield_lcd
#  These two dont work appearently because the slide changes when pb rolls. Should ride over the other slide but somehow it does not.  Might be able to add them to sis lat and sis medial modes testing for mb running
#  bonus_cnt_pb_rolled_lateral_hit:
#    big_rainbow_top_to_bottom:
#      target: playfield_lcd
#  bonus_cnt_pb_rolled_medial_hit:
#    rainbow_diagnal_top_left_to_bottom_right:
#      target: playfield_lcd
  ball_drain:
    big_rainbow_bottom_to_top:
      target: playfield_lcd
  ballblock_hit:
    big_rainbow_top_to_bottom:
      target: playfield_lcd
  base_olympus_spinner_hit:
    rainbow_diagnal_top_right_to_bottom_left:
      target: playfield_lcd

widgets:
  big_rainbow_left_to_right:
      type: image
      image: rainbow_side_big
      scale: .65
      y: 50%
      x: 50%
      anchor_x: middle
      anchor_y: middle
      rotation: 180
      loops: 0
      expire: 500ms
      fps: 45

  big_rainbow_right_to_left:
      type: image
      image: rainbow_side_big
      scale: .65
      y: 50%
      x: 50%
      anchor_x: middle
      anchor_y: middle
      rotation: 0
      loops: 0
      expire: 500ms
      fps: 45
  big_rainbow_top_to_bottom:
      type: image
      image: rainbow_side_big
      scale: .65
      y: 50%
      x: 50%
      anchor_x: middle
      anchor_y: middle
      rotation: 90
      loops: 0
      expire: 500ms
      fps: 45

  big_rainbow_bottom_to_top:
      type: image
      image: rainbow_side_big
      scale: .65
      y: 50%
      x: 50%
      anchor_x: middle
      anchor_y: middle
      rotation: -90
      loops: 0
      expire: 500ms
      fps: 45

  rainbow_diagnal_bottom_left_to_top_right:
      type: image
      image: rainbow_diagnal
      scale: .65
      y: 50%
      x: 50%
      anchor_x: middle
      anchor_y: middle
      rotation: 180
      loops: 0
      expire: 500ms
      fps: 30

  rainbow_diagnal_bottom_right_to_top_left:
      type: image
      image: rainbow_diagnal
      scale: .65
      y: 50%
      x: 50%
      anchor_x: middle
      anchor_y: middle
      rotation: -90
      loops: 0
      expire: 500ms
      fps: 30

  rainbow_diagnal_top_right_to_bottom_left:
    type: image
    image: rainbow_diagnal
    scale: .65
    y: 50%
    x: 50%
    anchor_x: middle
    anchor_y: middle
    rotation: 0
    loops: 0
    expire: 500ms
    fps: 30

  rainbow_diagnal_top_left_to_bottom_right:
    type: image
    image: rainbow_diagnal
    scale: .65
    y: 50%
    x: 50%
    anchor_x: middle
    anchor_y: middle
    rotation: 90
    loops: 0
    expire: 500ms
    fps: 30
