#config_version=5
# This mode starts on a double hit to the right ramp.  It shuts down if the ball save is used or a 1 min timer expires. It set up a shot for the right outlane that will disable during mb.
# It uses a multiball without a shoot again to serve the ball.
mode:
  priority: 2580 # range 100-1M
  start_events:
    - double_right_ramp_hit
  stop_events:
    - ball_ended
    - multiball_right_outlane_started
    - timer_right_bs_expiration_complete

multiballs:
  right_outlane:
    source_playfield: earth_pf
    ball_count: 1
    ball_count_type: add #total # increase number of playfield balls to count
    shoot_again: 0s #ball save for MB 10 sec default
    start_events: right_outlane_banked_ballsave_hit
    debug: true

display_light_player: #http://docs.missionpinball.org/en/latest/config/display_light_player.html?highlight=display_light_player
  mode_banked_r_bs_started: #started.100 for higher priority?
    led_matrix:
      action: play  #Default
      lights: gi, insert  #right_orbit
  banked_r_bs_wipe_done: #Otherwise the mode hangs
    led_matrix:
      action: stop
      lights: gi, insert

timers:
  right_bs_expiration:
    start_value: 4
    end_value: 0
    direction: down
    tick_interval: 15s
    control_events:
      - event: mode_banked_r_bs_started
        action: restart #reset to starting value and start
      - event: banked_r_ballsave_double_right_ramp_hit{device.timers.right_bs_expiration.ticks<6}
        action: add
        value: 2

shots:
  right_outlane_banked_ballsave:  # When shot is hit it triggers a 1 ball MB effectively returning ball to play
    playfield: earth_pf
    disable_events:
      - multiball_poseidon_ramp_started #disable when a mb starts.
      - multiball_olympus_ramp_started  #add hidden hole mb when written
    enable_events:
      - mode_banked_r_bs_started
      - multiball_poseidon_ramp_ended #re-enable when a mb ends.  This should not start the mode if not already running.
      - multiball_olympus_ramp_ended  #add hidden hole mb when written
    switches:
      - s_right_outlane
  banked_r_ballsave_double_right_ramp: #used to add time to banked ball save mode
    playfield: earth_pf
    profile: off_on
    enable_events:
      - timer_base_right_ramp_tick{device.timers.base_right_ramp.ticks==3}
    disable_events:
      - timer_base_right_ramp_complete
    hit_events:
      - right_ramp_hit

show_player:
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks>5}:
    show_right_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_3:
      action: stop_l_bs
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6: #Start the beginning show
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==5}:
    show_right_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_5: #Start the beginning show
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==4}:
    show_right_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_4: #Start the beginning show
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==3}:
    show_right_shoulder_1:
      action: stop
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_3:
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==2}:
    show_right_shoulder_1:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_2:
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==1}:
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_1:
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==0}:
    show_right_shoulder_1:
      action: stop

#Playfield Display width: 508 height: 1190
#> 1000 or 84% is BB < 980 upper apron; < 920 orbit

slide_player:
  mode_banked_r_bs_started:
    ark_sweep_right:
      target: led_matrix
      background_color: 00000000 #Background with no opacity required
      widgets:
      - type: bezier
#        points: 0,1060,    433,960,    508,760
        points: 0,760,    75,960,    508,1060
        thickness: 90
        color: red
        anchor_x: top
        anchor_y: left
        expire: 0.5s
        events_when_removed: banked_l_bs_wipe_done
        animations:
          show_slide:
            - property: points
              value: 400,-1000,   400,-1000,   400,-1000
              relative: true
              duration: 0.5s

sound_player:
  mode_banked_r_bs_started: comboballsavelocked
  banked_r_ballsave_double_right_ramp_hit{device.timers.right_bs_expiration.ticks<6}: timeadded
