#config_version=5
# This mode starts on a double hit to the right ramp.  It shuts down if the ball save
# is used, the ball ends or the mode timer expires. Time can be added to the mode timer
# with additional shots to the ramp. The mode works by setting up an outlane shot that
# when hit starts the ball save/timer. When activated the bs posts ball_save_(name)_timer_start
# that I coopt as the ball save's early ball save event.
# Also this mode runs the show that indictes the ball save is available.
# When a mb is running the timer that ends this mode pauses for the duration of the mb
# shoot again. Also the shot that activates the ball save is taken off line for the
# shoot again period so as not to be used up when there is already a mechanism for
# returning the ball to play.
# This mode requires the events from base:
#     base_double_right_ramp_hit (double rampt shot to activate)
#     right_ramp_hit (sequence shot that add more time to mode if time M 1.5 min)
mode:
  priority: 2580 # range 100-1M
  start_events:
    - base_double_right_ramp_hit
    - bottom_lane_group_hit_complete #completed all 4 bottom lanes.
  stop_events:
    - ball_ended
    - ball_save_banked_right_saving_ball
    - timer_right_bs_expiration_complete

ball_saves:
  banked_right:
    enable_events: right_outlane_banked_ballsave_hit
#    timer_start_events: right_outlane_banked_ballsave_hit
    early_ball_save_events:
       - ball_save_banked_right_timer_start #This is automatically issued from the ball save routines
#      - timer_right_bs_lane_triggered_complete
    auto_launch: yes
    active_time: 1s
    hurry_up_time: 0s
    grace_period: 0s
    balls_to_save: 1
    source_playfield: earth_pf
    debug: no

timers:
#  right_bs_lane_triggered:
#    start_value: 1
#    end_value: 0
#    direction: down
#    tick_interval: 100ms
#    control_events:
#      - event: right_outlane_banked_ballsave_hit
#        action: restart
  right_bs_expiration:
    start_value: 4
    end_value: 0
    direction: down
    tick_interval: 15s
    control_events:
      - event: mode_banked_r_bs_started
        action: restart #reset to starting value and start
      - event: right_ramp_hit{device.timers.right_bs_expiration.ticks<=6}
        action: add
        value: 2
      - event: bottom_lane_group_hit_complete #Give a time bonus if already running
        action: add
        value: 2
      - event: multiball_poseidon_ramp_started
        action: pause
        value: 10 #Not ticks, but seconds, in this case the duration of the shoot again  This might be a problem if both mb act at same time, get double pause or potential for race condition depending on back end code.
      - event: multiball_olympus_ramp_started
        action: pause
        value: 10 #Not ticks, but seconds, in this case the duration of the shoot again  This might be a problem if both mb act at same time, get double pause or potential for race condition depending on back end code.

shots:
  right_outlane_banked_ballsave:  # When shot is hit it triggers a 1 ball MB effectively returning ball to play
    playfield: earth_pf
    disable_events:
      - multiball_poseidon_ramp_started #disable when a mb starts.
      - multiball_olympus_ramp_started  #add hidden hole mb when written
    enable_events:
      - mode_banked_r_bs_started
      - multiball_poseidon_ramp_shoot_again_ended #re-enable when a mb ball save ends.
      - multiball_olympus_ramp_shoot_again_ended  #add for goddess mb
    switches:
      - s_right_outlane

show_player:
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks>5}:
    show_right_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6: #Start the beginning show
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==5}:
    show_right_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_5: #Start the beginning show
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==4}:
    show_right_shoulder_1: #Stop an old show if timer reset
      action: stop
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_4: #Start the beginning show
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==3}:
    show_right_shoulder_1:
      action: stop
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_3:
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==2}:
    show_right_shoulder_1:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_2:
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==1}:
    show_right_shoulder_2:
      action: stop
    show_right_shoulder_3:
      action: stop
    show_right_shoulder_4:
      action: stop
    show_right_shoulder_5:
      action: stop
    show_right_shoulder_6:
      action: stop
    show_right_shoulder_1:
      speed: 10
      action: play
  timer_right_bs_expiration_tick{device.timers.right_bs_expiration.ticks==0}:
    show_right_shoulder_1:
      action: stop


sound_player:
#  mode_banked_r_bs_started: v_right_outlane_bs_awarded moved to sound effects mode 
  ball_save_banked_right_saving_ball: v_ball_saved
  right_ramp_hit{device.timers.right_bs_expiration.ticks<=6}: v_time_added
